In [6]:
import pandas as pd

file_path = "/Users/inqsoncharoen/Documents/RStudio Module/charts.csv"
df = pd.read_csv(file_path)

df.head()

,date,rank,song,artist,last-week,peak-rank,weeks-on-board
0,2021-11-06,1,Easy On Me,Adele,1.0,1,3
1,2021-11-06,2,Stay,The Kid LAROI & Justin Bieber,2.0,1,16
2,2021-11-06,3,Industry Baby,Lil Nas X & Jack Harlow,3.0,1,14
3,2021-11-06,4,Fancy Like,Walker Hayes,4.0,3,19
4,2021-11-06,5,Bad Habits,Ed Sheeran,5.0,2,18

Here, I am just trying to turn the Billboard csv (that we initially thought we'd work with, but had API problems later) into a yearly one. The original one has weekly updates to it so there are a lot of repeats. I dealt with this by giving a score, summing it, and ranking the overall one to produce a yearly chart.

In [7]:

df["date"] = pd.to_datetime(df["date"])
df["year"] = df["date"].dt.year

df["score"] = 101 - df["rank"]

yearly_chart = (df.groupby(["year", "song", "artist"])["score"]
                  .sum()
                  .reset_index())

yearly_chart = yearly_chart.sort_values(by=["year", "score"], ascending=[True, False])
yearly_chart[yearly_chart["year"] == 2021].head(10)

,year,song,artist,score
35484,2021,Blinding Lights,The Weeknd,3137
35713,2021,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),2942
35782,2021,Montero (Call Me By Your Name),Lil Nas X,2789
35723,2021,Levitating,Dua Lipa Featuring DaBaby,2737
35702,2021,Kiss Me More,Doja Cat Featuring SZA,2733
35783,2021,Mood,24kGoldn Featuring iann dior,2694
35845,2021,Peaches,Justin Bieber Featuring Daniel Caesar & Giveon,2595
35638,2021,Heat Waves,Glass Animals,2550
35552,2021,Drivers License,Olivia Rodrigo,2485
35537,2021,Deja Vu,Olivia Rodrigo,2466

In [9]:
output_file_path = "/Users/inqsoncharoen/Documents/RStudio Module/yearly_billboard_chart.csv"
yearly_chart.to_csv(output_file_path, index=False)

output_file_path


# d = {}
# for g, n in df_new.groupby(level=0):
#     d[g] = n.loc[:,n.sum().rank(ascending=False,method='min')<5]
    
#print(d[2018])
#print(d[2019])

'/Users/inqsoncharoen/Documents/RStudio Module/yearly_billboard_chart.csv'

In [ ]:
import requests
import base64

SPOTIPY_CLIENT_ID = "my secret!!"
SPOTIPY_CLIENT_SECRET = "my secret!!"

url = "https://accounts.spotify.com/api/token" #I used this to check my access token
headers = {
    "Authorization": "Basic " + base64.b64encode(f"{SPOTIPY_CLIENT_ID}:{SPOTIPY_CLIENT_SECRET}".encode()).decode(),
    "Content-Type": "application/x-www-form-urlencoded",
}
data = {"grant_type": "client_credentials"}

response = requests.post(url, headers=headers, data=data)

if response.status_code == 200:
    access_token = response.json().get("access_token")
    print(f"Access Token: {access_token}")
else:
    print(f"Error: {response.status_code}, Response: {response.json()}")

✅ Access Token: BQBXglqva0UyhbBTdtweID392MNJ_nEGef_JrvSGPWTEUNdnBjPlHTDsdNWKEV-EZh5nmalVTO1v4B0TENwr7jO7ynCqqDCpfC39hwewbFHIrhmg4FxUKGq47Mi9OGOy7jqH8lt3psU

I had massive issues with this part. I checked and I successfully obtained an access token, I got it to print it explicitly since I initially had issues about it. The access token part was solved. As written in the report, I spent the last two days before the (assumed) deadline figuring it out, and the problem runs deeper than just having the token -- it's also to do with Jupyter occupying its usual 8888 server. I tried forcing it onto other servers, but still didn't work. We didn't have time to work on that, nor did we have time to troubleshoot this part, that would've otherwise worked with Billboard data.

In [ ]:
import spotipy
import requests
from spotipy.oauth2 import SpotifyClientCredentials

SPOTIPY_CLIENT_ID = "572eb4f3685b49349cbd2517ac8c064e"
SPOTIPY_CLIENT_SECRET = "0e6ba40bf0e74257a939dabfb2019b9d"

url = "https://accounts.spotify.com/api/token" #MANUALLY GET IT UGHHHHHSAFJKDFJDAJ
headers = {
    "Authorization": "Basic " + base64.b64encode(f"{SPOTIPY_CLIENT_ID}:{SPOTIPY_CLIENT_SECRET}".encode()).decode(),
    "Content-Type": "application/x-www-form-urlencoded",
}
data = {"grant_type": "client_credentials"}

response = requests.post(url, headers=headers, data=data)
token = response.json().get("access_token")

sp = spotipy.Spotify(auth=token) #TRYING TO SET IT MANUALLY AHHHH AND IT STILL DOESNT WORK

In [10]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
import time

file_path = "/Users/inqsoncharoen/Documents/RStudio Module/yearly_billboard_chart.csv"
df = pd.read_csv(file_path)

SPOTIPY_CLIENT_ID = "572eb4f3685b49349cbd2517ac8c064e"
SPOTIPY_CLIENT_SECRET = "0e6ba40bf0e74257a939dabfb2019b9d"

# Manually fetch token
client_credentials_manager = SpotifyClientCredentials(client_id=SPOTIPY_CLIENT_ID, client_secret=SPOTIPY_CLIENT_SECRET)
token = client_credentials_manager.get_access_token()

if not token:
    raise Exception("❌ Failed to get a valid token. Check your credentials.")

# Initialize Spotipy with the valid token
sp = spotipy.Spotify(auth=token)

print("✅ Successfully authenticated!")

/var/folders/hb/qtg2k1095t583b4c_cgh3d000000gn/T/ipykernel_3926/2355243210.py:14: DeprecationWarning: You're using 'as_dict = True'.get_access_token will return the token string directly in future versions. Please adjust your code accordingly, or use get_cached_token instead.
  token = client_credentials_manager.get_access_token()
WARNING:spotipy.cache_handler:Couldn't write token to cache at: .cache

✅ Successfully authenticated!

As for the cell below, I tried working on the function on my own. The get_valence() function had no issues on its own, but had 403 error (no access token issue, can't get to it on the Spotify API end). If it looks weird, it's because I got a little frustrated, and asked ChatGPT to check it and it added emojis to "check" my code and all. I have a programming background, so I know what ChatGPT was trying to do / if it was giving code consistent to my interpretation. But, it still didn't work on the Spotify end. I ran things on my computer's terminal (bash) and yeah, it wasn't  wrong syntax or that a ChatGPT correction was needed at all. The issue was much deeper.

In [ ]:
def get_valence(song, artist):
    try:
        song = song.replace(",", "").strip()
        artist = artist.replace(",", "").strip()

        query = f"{song} {artist}"
        print(f"Searching for: {query}")
        results = sp.search(q=query, type="track", limit=1)
        
        print(f"Results: {results}")

        if not results['tracks']['items']:
            print(f"⚠️ Skipping: No results for {song} by {artist}")
            return None

        track_id = results['tracks']['items'][0]['id']
        features = sp.audio_features(track_id)
        
        print(f"Features: {features}")

        if features and len(features) > 0 and 'valence' in features[0]:
            return features[0]['valence']
        else:
            print(f"⚠️ Skipping: No valence data for {song} by {artist}")
            return None
    except Exception as e:
        print(f"❌ Error retrieving valence for {song} by {artist}: {e}")
        return None


# Apply valence function to each row in DataFrame
df['valence'] = df.apply(lambda row: get_valence(row['song'], row['artist']), axis=1)

# Save updated CSV
output_file = "yearly_billboard_chart_with_valence.csv"
df.to_csv(output_file, index=False)

print(f"✅ Updated CSV saved as {output_file}")

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Chantilly Lace Big Bopper', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "It's All In The Game Tommy Edwards", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Rock-in Robin Bobby Day', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

Searching for: Chantilly Lace Big Bopper
❌ Error retrieving valence for Chantilly Lace by Big Bopper: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Chantilly+Lace+Big+Bopper&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: It's All In The Game Tommy Edwards
❌ Error retrieving valence for It's All In The Game by Tommy Edwards: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=It%27s+All+In+The+Game+Tommy+Edwards&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Rock-in Robin Bobby Day
❌ Error retrieving valence for Rock-in Robin by Bobby Day: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Rock-in+Robin+Bobby+Day&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Bird Dog The Everly Brothers

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Bird Dog The Everly Brothers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Topsy II Cozy Cole', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Little Star The Elegants', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "It's Only Make Believe Conway Twitty", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Tears On My Pillow Little Anthony And The Imperials', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Tea For Two Cha Cha The Tommy Dorsey Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Bird Dog by The Everly Brothers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Bird+Dog+The+Everly+Brothers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Topsy II Cozy Cole
❌ Error retrieving valence for Topsy II by Cozy Cole: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Topsy+II+Cozy+Cole&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Little Star The Elegants
❌ Error retrieving valence for Little Star by The Elegants: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Little+Star+The+Elegants&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: It's Only Make Believe Conway Twitty
❌ Error retrieving valence for It's Only Make Believe by Conway Twitty: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=It%27s+Only+Make+Believe+Conway+Twitty&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Tears On My Pillow Little Anthony And The Imperials
❌ Error retrieving valence for Tears On My Pillow by Little Anthony And The Imperials: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Tears+On+My+Pillow+Little+Anthony+And+The+Imperials&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Tea For Two Cha Cha The Tommy Dorsey Orchestra
❌ Error retrieving valence for Tea For Two Cha Cha by The Tommy Dorsey Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Tea+For+Two+Cha+Cha+The+Tommy+Dorsey+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Susie Darlin' Robin Luke

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Susie Darlin' Robin Luke", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Nel Blu Dipinto Di Blu (Volaré) Domenico Modugno', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The End Earl Grant', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Tom Dooley The Kingston Trio', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Just A Dream Jimmy Clanton And His Rockets', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'To Know Him Is To Love Him The Teddy Bears', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Susie Darlin' by Robin Luke: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Susie+Darlin%27+Robin+Luke&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Nel Blu Dipinto Di Blu (Volaré) Domenico Modugno
❌ Error retrieving valence for Nel Blu Dipinto Di Blu (Volaré) by Domenico Modugno: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Nel+Blu+Dipinto+Di+Blu+%28Volar%C3%A9%29+Domenico+Modugno&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The End Earl Grant
❌ Error retrieving valence for The End by Earl Grant: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+End+Earl+Grant&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Tom Dooley The Kingston Trio
❌ Error retrieving valence for Tom Dooley by The Kingston Trio: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Tom+Dooley+The+Kingston+Trio&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Just A Dream Jimmy Clanton And His Rockets
❌ Error retrieving valence for Just A Dream by Jimmy Clanton And His Rockets: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Just+A+Dream+Jimmy+Clanton+And+His+Rockets&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: To Know Him Is To Love Him The Teddy Bears
❌ Error retrieving valence for To Know Him Is To Love Him by The Teddy Bears: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=To+Know+Him+Is+To+Love+Him+The+Teddy+Bears&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Summertime Blues Eddie Cochran

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Summertime Blues Eddie Cochran', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Near You Roger Williams', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Born Too Late Poni-Tails', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'My True Love Jack Scott', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Patricia Perez Prado And His Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Devoted To You The Everly Brothers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Summertime Blues by Eddie Cochran: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Summertime+Blues+Eddie+Cochran&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Near You Roger Williams
❌ Error retrieving valence for Near You by Roger Williams: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Near+You+Roger+Williams&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Born Too Late Poni-Tails
❌ Error retrieving valence for Born Too Late by Poni-Tails: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Born+Too+Late+Poni-Tails&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: My True Love Jack Scott
❌ Error retrieving valence for My True Love by Jack Scott: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=My+True+Love+Jack+Scott&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Patricia Perez Prado And His Orchestra
❌ Error retrieving valence for Patricia by Perez Prado And His Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Patricia+Perez+Prado+And+His+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Devoted To You The Everly Brothers
❌ Error retrieving valence for Devoted To You by The Everly Brothers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Devoted+To+You+The+Everly+Brothers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I Got A Feeling Ricky Nelson

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'I Got A Feeling Ricky Nelson', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'How The Time Flies Jerry Wallace', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Day The Rains Came Jane Morgan', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Queen Of The Hop Bobby Darin', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Lonesome Town Ricky Nelson', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Pussy Cat The Ames Brothers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Mexican Hat Rock The Applejacks', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for I Got A Feeling by Ricky Nelson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I+Got+A+Feeling+Ricky+Nelson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: How The Time Flies Jerry Wallace
❌ Error retrieving valence for How The Time Flies by Jerry Wallace: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=How+The+Time+Flies+Jerry+Wallace&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Day The Rains Came Jane Morgan
❌ Error retrieving valence for The Day The Rains Came by Jane Morgan: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Day+The+Rains+Came+Jane+Morgan&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Queen Of The Hop Bobby Darin
❌ Error retrieving valence for Queen Of The Hop by Bobby Darin: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Queen+Of+The+Hop+Bobby+Darin&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Lonesome Town Ricky Nelson
❌ Error retrieving valence for Lonesome Town by Ricky Nelson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Lonesome+Town+Ricky+Nelson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Pussy Cat The Ames Brothers
❌ Error retrieving valence for Pussy Cat by The Ames Brothers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Pussy+Cat+The+Ames+Brothers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Mexican Hat Rock The Applejacks
❌ Error retrieving valence for Mexican Hat Rock by The Applejacks: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Mexican+Hat+Rock+The+Applejacks&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: You Cheated The Shields

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'You Cheated The Shields', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Poor Little Fool Ricky Nelson', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Western Movies The Olympics', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'There Goes My Heart Joni James', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Call Me Johnny Mathis', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Fever Peggy Lee', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for You Cheated by The Shields: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=You+Cheated+The+Shields&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Poor Little Fool Ricky Nelson
❌ Error retrieving valence for Poor Little Fool by Ricky Nelson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Poor+Little+Fool+Ricky+Nelson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Western Movies The Olympics
❌ Error retrieving valence for Western Movies by The Olympics: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Western+Movies+The+Olympics&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: There Goes My Heart Joni James
❌ Error retrieving valence for There Goes My Heart by Joni James: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=There+Goes+My+Heart+Joni+James&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Call Me Johnny Mathis
❌ Error retrieving valence for Call Me by Johnny Mathis: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Call+Me+Johnny+Mathis&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Fever Peggy Lee
❌ Error retrieving valence for Fever by Peggy Lee: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Fever+Peggy+Lee&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Everybody Loves A Lover Doris Day

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Everybody Loves A Lover Doris Day', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Are You Really Mine Jimmie Rodgers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "A Lover's Question Clyde McPhatter", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Somebody Touched Me Buddy Knox with the Rhythm Orchids', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Stupid Cupid Connie Francis', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Forget Me Not Kalin Twins', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'No One Knows Dion & The Belmonts', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Everybody Loves A Lover by Doris Day: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Everybody+Loves+A+Lover+Doris+Day&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Are You Really Mine Jimmie Rodgers
❌ Error retrieving valence for Are You Really Mine by Jimmie Rodgers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Are+You+Really+Mine+Jimmie+Rodgers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: A Lover's Question Clyde McPhatter
❌ Error retrieving valence for A Lover's Question by Clyde McPhatter: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=A+Lover%27s+Question+Clyde+McPhatter&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Somebody Touched Me Buddy Knox with the Rhythm Orchids
❌ Error retrieving valence for Somebody Touched Me by Buddy Knox with the Rhythm Orchids: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Somebody+Touched+Me+Buddy+Knox+with+the+Rhythm+Orchids&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Stupid Cupid Connie Francis
❌ Error retrieving valence for Stupid Cupid by Connie Francis: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Stupid+Cupid+Connie+Francis&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Forget Me Not Kalin Twins
❌ Error retrieving valence for Forget Me Not by Kalin Twins: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Forget+Me+Not+Kalin+Twins&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: No One Knows Dion & The Belmonts
❌ Error retrieving valence for No One Knows by Dion & The Belmonts: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=No+One+Knows+Dion+%26+The+Belmonts&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Hideaway The Four Esquires

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Hideaway The Four Esquires', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Win Your Love For Me Sam Cooke', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Beep Beep The Playmates', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Poor Boy The Royaltones', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Firefly Tony Bennett', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Ginger Bread Frankie Avalon', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Hideaway by The Four Esquires: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Hideaway+The+Four+Esquires&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Win Your Love For Me Sam Cooke
❌ Error retrieving valence for Win Your Love For Me by Sam Cooke: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Win+Your+Love+For+Me+Sam+Cooke&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Beep Beep The Playmates
❌ Error retrieving valence for Beep Beep by The Playmates: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Beep+Beep+The+Playmates&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Poor Boy The Royaltones
❌ Error retrieving valence for Poor Boy by The Royaltones: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Poor+Boy+The+Royaltones&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Firefly Tony Bennett
❌ Error retrieving valence for Firefly by Tony Bennett: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Firefly+Tony+Bennett&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Ginger Bread Frankie Avalon
❌ Error retrieving valence for Ginger Bread by Frankie Avalon: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Ginger+Bread+Frankie+Avalon&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Ten Commandments Of Love Harvey & The Moonglows

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Ten Commandments Of Love Harvey & The Moonglows', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Volare (Nel Blu Dipinto Di Blu) Dean Martin', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Need You Donnie Owens', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'I Got Stung Elvis Presley', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Willie And The Hand Jive The Johnny Otis Show', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Itchy Twitchy Feeling Bobby Hendricks', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'One Night Elvis Presley', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Ten Commandments Of Love by Harvey & The Moonglows: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Ten+Commandments+Of+Love+Harvey+%26+The+Moonglows&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Volare (Nel Blu Dipinto Di Blu) Dean Martin
❌ Error retrieving valence for Volare (Nel Blu Dipinto Di Blu) by Dean Martin: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Volare+%28Nel+Blu+Dipinto+Di+Blu%29+Dean+Martin&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Need You Donnie Owens
❌ Error retrieving valence for Need You by Donnie Owens: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Need+You+Donnie+Owens&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I Got Stung Elvis Presley
❌ Error retrieving valence for I Got Stung by Elvis Presley: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I+Got+Stung+Elvis+Presley&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Willie And The Hand Jive The Johnny Otis Show
❌ Error retrieving valence for Willie And The Hand Jive by The Johnny Otis Show: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Willie+And+The+Hand+Jive+The+Johnny+Otis+Show&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Itchy Twitchy Feeling Bobby Hendricks
❌ Error retrieving valence for Itchy Twitchy Feeling by Bobby Hendricks: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Itchy+Twitchy+Feeling+Bobby+Hendricks&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: One Night Elvis Presley
❌ Error retrieving valence for One Night by Elvis Presley: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=One+Night+Elvis+Presley&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I'll Wait For You Frankie Avalon

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "I'll Wait For You Frankie Avalon", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Problems The Everly Brothers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Secret Gordon MacRae', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Love Is All We Need Tommy Edwards', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Promise Me Love Andy Williams', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'When Kalin Twins', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for I'll Wait For You by Frankie Avalon: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I%27ll+Wait+For+You+Frankie+Avalon&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Problems The Everly Brothers
❌ Error retrieving valence for Problems by The Everly Brothers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Problems+The+Everly+Brothers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Secret Gordon MacRae
❌ Error retrieving valence for The Secret by Gordon MacRae: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Secret+Gordon+MacRae&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Love Is All We Need Tommy Edwards
❌ Error retrieving valence for Love Is All We Need by Tommy Edwards: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Love+Is+All+We+Need+Tommy+Edwards&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Promise Me Love Andy Williams
❌ Error retrieving valence for Promise Me Love by Andy Williams: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Promise+Me+Love+Andy+Williams&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: When Kalin Twins
❌ Error retrieving valence for When by Kalin Twins: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=When+Kalin+Twins&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Treasure Of Your Love Eileen Rodgers

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Treasure Of Your Love Eileen Rodgers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Down The Aisle Of Love The Quin-Tones', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Rebel-'rouser Duane Eddy His Twangy Guitar And The Rebels", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'A Letter To An Angel Jimmy Clanton', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Carol Chuck Berry', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Treasure Of Your Love by Eileen Rodgers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Treasure+Of+Your+Love+Eileen+Rodgers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Down The Aisle Of Love The Quin-Tones
❌ Error retrieving valence for Down The Aisle Of Love by The Quin-Tones: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Down+The+Aisle+Of+Love+The+Quin-Tones&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Rebel-'rouser Duane Eddy His Twangy Guitar And The Rebels
❌ Error retrieving valence for Rebel-'rouser by Duane Eddy His Twangy Guitar And The Rebels: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Rebel-%27rouser+Duane+Eddy+His+Twangy+Guitar+And+The+Rebels&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: A Letter To An Angel Jimmy Clanton
❌ Error retrieving valence for A Letter To An Angel by Jimmy Clanton: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=A+Letter+To+An+Angel+Jimmy+Clanton&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Carol Chuck Berry
❌ Error retrieving valence for Carol by Chuck Berry: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Carol+Chuck+Berry&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: For My Good Fortune Pat Boone

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'For My Good Fortune Pat Boone', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Cannonball Duane Eddy His Twangy Guitar And The Rebels', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for For My Good Fortune by Pat Boone: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=For+My+Good+Fortune+Pat+Boone&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Cannonball Duane Eddy His Twangy Guitar And The Rebels
❌ Error retrieving valence for Cannonball by Duane Eddy His Twangy Guitar And The Rebels: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Cannonball+Duane+Eddy+His+Twangy+Guitar+And+The+Rebels&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: If Dreams Came True Pat Boone

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'If Dreams Came True Pat Boone', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'She Was Only Seventeen (He Was One Year More) Marty Robbins', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for If Dreams Came True by Pat Boone: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=If+Dreams+Came+True+Pat+Boone&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: She Was Only Seventeen (He Was One Year More) Marty Robbins
❌ Error retrieving valence for She Was Only Seventeen (He Was One Year More) by Marty Robbins: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=She+Was+Only+Seventeen+%28He+Was+One+Year+More%29+Marty+Robbins&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Splish Splash Bobby Darin

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Splish Splash Bobby Darin', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Lazy Summer Night The Four Preps', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Bimbombey Jimmie Rodgers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'One Summer Night The Danleers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Splish Splash by Bobby Darin: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Splish+Splash+Bobby+Darin&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Lazy Summer Night The Four Preps
❌ Error retrieving valence for Lazy Summer Night by The Four Preps: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Lazy+Summer+Night+The+Four+Preps&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Bimbombey Jimmie Rodgers
❌ Error retrieving valence for Bimbombey by Jimmie Rodgers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Bimbombey+Jimmie+Rodgers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: One Summer Night The Danleers
❌ Error retrieving valence for One Summer Night by The Danleers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=One+Summer+Night+The+Danleers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Topsy I Cozy Cole

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Topsy I Cozy Cole', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "I'll Remember Tonight Pat Boone", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Smoke Gets In Your Eyes The Platters', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Walking Along The Diamonds', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Topsy I by Cozy Cole: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Topsy+I+Cozy+Cole&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I'll Remember Tonight Pat Boone
❌ Error retrieving valence for I'll Remember Tonight by Pat Boone: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I%27ll+Remember+Tonight+Pat+Boone&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Smoke Gets In Your Eyes The Platters
❌ Error retrieving valence for Smoke Gets In Your Eyes by The Platters: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Smoke+Gets+In+Your+Eyes+The+Platters&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Walking Along The Diamonds
❌ Error retrieving valence for Walking Along by The Diamonds: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Walking+Along+The+Diamonds&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Summertime Summertime The Jamies

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Summertime Summertime The Jamies', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'A Certain Smile Johnny Mathis', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The World Outside The Four Coins', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Hard Headed Woman Elvis Presley With The Jordanaires', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Summertime Summertime by The Jamies: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Summertime+Summertime+The+Jamies&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: A Certain Smile Johnny Mathis
❌ Error retrieving valence for A Certain Smile by Johnny Mathis: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=A+Certain+Smile+Johnny+Mathis&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The World Outside The Four Coins
❌ Error retrieving valence for The World Outside by The Four Coins: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+World+Outside+The+Four+Coins&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Hard Headed Woman Elvis Presley With The Jordanaires
❌ Error retrieving valence for Hard Headed Woman by Elvis Presley With The Jordanaires: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Hard+Headed+Woman+Elvis+Presley+With+The+Jordanaires&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Moon Talk Perry Como

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Moon Talk Perry Como', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'That Old Black Magic Louis Prima And Keely Smith', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Whole Lotta Loving Fats Domino', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'La-Do-Dada Dale Hawkins', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Put A Ring On My Finger Les Paul And Mary Ford', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Moon Talk by Perry Como: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Moon+Talk+Perry+Como&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: That Old Black Magic Louis Prima And Keely Smith
❌ Error retrieving valence for That Old Black Magic by Louis Prima And Keely Smith: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=That+Old+Black+Magic+Louis+Prima+And+Keely+Smith&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Whole Lotta Loving Fats Domino
❌ Error retrieving valence for Whole Lotta Loving by Fats Domino: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Whole+Lotta+Loving+Fats+Domino&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: La-Do-Dada Dale Hawkins
❌ Error retrieving valence for La-Do-Dada by Dale Hawkins: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=La-Do-Dada+Dale+Hawkins&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Put A Ring On My Finger Les Paul And Mary Ford
❌ Error retrieving valence for Put A Ring On My Finger by Les Paul And Mary Ford: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Put+A+Ring+On+My+Finger+Les+Paul+And+Mary+Ford&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: La Paloma Billy Vaughn And His Orchestra

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'La Paloma Billy Vaughn And His Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'With Your Love Jack Scott', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Early In The Morning The Rinky-Dinks', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Left Right Out Of Your Heart (Hi Lee Hi Lo Hi Lup Up Up) Patti Page', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Ways Of A Woman In Love Johnny Cash And The Tennessee Two', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for La Paloma by Billy Vaughn And His Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=La+Paloma+Billy+Vaughn+And+His+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: With Your Love Jack Scott
❌ Error retrieving valence for With Your Love by Jack Scott: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=With+Your+Love+Jack+Scott&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Early In The Morning The Rinky-Dinks
❌ Error retrieving valence for Early In The Morning by The Rinky-Dinks: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Early+In+The+Morning+The+Rinky-Dinks&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Left Right Out Of Your Heart (Hi Lee Hi Lo Hi Lup Up Up) Patti Page
❌ Error retrieving valence for Left Right Out Of Your Heart (Hi Lee Hi Lo Hi Lup Up Up) by Patti Page: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Left+Right+Out+Of+Your+Heart+%28Hi+Lee+Hi+Lo+Hi+Lup+Up+Up%29+Patti+Page&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Ways Of A Woman In Love Johnny Cash And The Tennessee Two
❌ Error retrieving valence for The Ways Of A Woman In Love by Johnny Cash And The Tennessee Two: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Ways+Of+A+Woman+In+Love+Johnny+Cash+And+The+Tennessee+Two&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Non Dimenticar (Don't Forget) Nat King Cole

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Non Dimenticar (Don't Forget) Nat King Cole", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Over And Over Bobby Day', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Come Closer To Me (Acercate Mas) Nat King Cole', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Mocking Bird The Four Lads', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Non Dimenticar (Don't Forget) by Nat King Cole: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Non+Dimenticar+%28Don%27t+Forget%29+Nat+King+Cole&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Over And Over Bobby Day
❌ Error retrieving valence for Over And Over by Bobby Day: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Over+And+Over+Bobby+Day&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Come Closer To Me (Acercate Mas) Nat King Cole
❌ Error retrieving valence for Come Closer To Me (Acercate Mas) by Nat King Cole: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Come+Closer+To+Me+%28Acercate+Mas%29+Nat+King+Cole&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Mocking Bird The Four Lads
❌ Error retrieving valence for The Mocking Bird by The Four Lads: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Mocking+Bird+The+Four+Lads&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Day The Rains Came Raymond Lefevre and His Orchestra

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Day The Rains Came Raymond Lefevre and His Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Yakety Yak The Coasters', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "This Little Girl's Gone Rockin' Ruth Brown", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Love Makes The World Go 'round Perry Como", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Blob The Five Blobs', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for The Day The Rains Came by Raymond Lefevre and His Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Day+The+Rains+Came+Raymond+Lefevre+and+His+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Yakety Yak The Coasters
❌ Error retrieving valence for Yakety Yak by The Coasters: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Yakety+Yak+The+Coasters&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: This Little Girl's Gone Rockin' Ruth Brown
❌ Error retrieving valence for This Little Girl's Gone Rockin' by Ruth Brown: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=This+Little+Girl%27s+Gone+Rockin%27+Ruth+Brown&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Love Makes The World Go 'round Perry Como
❌ Error retrieving valence for Love Makes The World Go 'round by Perry Como: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Love+Makes+The+World+Go+%27round+Perry+Como&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Blob The Five Blobs
❌ Error retrieving valence for The Blob by The Five Blobs: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Blob+The+Five+Blobs&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Mr. Success Frank Sinatra

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Mr. Success Frank Sinatra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Early In The Morning Buddy Holly', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Think It Over The Crickets', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Fibbin' Patti Page", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Blue Blue Day Don Gibson', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Baby Face Little Richard', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Mr. Success by Frank Sinatra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Mr.+Success+Frank+Sinatra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Early In The Morning Buddy Holly
❌ Error retrieving valence for Early In The Morning by Buddy Holly: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Early+In+The+Morning+Buddy+Holly&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Think It Over The Crickets
❌ Error retrieving valence for Think It Over by The Crickets: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Think+It+Over+The+Crickets&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Fibbin' Patti Page
❌ Error retrieving valence for Fibbin' by Patti Page: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Fibbin%27+Patti+Page&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Blue Blue Day Don Gibson
❌ Error retrieving valence for Blue Blue Day by Don Gibson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Blue+Blue+Day+Don+Gibson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Baby Face Little Richard
❌ Error retrieving valence for Baby Face by Little Richard: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Baby+Face+Little+Richard&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Gee But It's Lonely Pat Boone

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Gee But It's Lonely Pat Boone", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'All Over Again Johnny Cash', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Fallin' Connie Francis", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Gotta Travel On Billy Grammer', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Betty Lou Got A New Pair Of Shoes Bobby Freeman', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Ramrod Duane Eddy His Twangy Guitar And The Rebels', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Gee But It's Lonely by Pat Boone: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Gee+But+It%27s+Lonely+Pat+Boone&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: All Over Again Johnny Cash
❌ Error retrieving valence for All Over Again by Johnny Cash: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=All+Over+Again+Johnny+Cash&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Fallin' Connie Francis
❌ Error retrieving valence for Fallin' by Connie Francis: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Fallin%27+Connie+Francis&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Gotta Travel On Billy Grammer
❌ Error retrieving valence for Gotta Travel On by Billy Grammer: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Gotta+Travel+On+Billy+Grammer&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Betty Lou Got A New Pair Of Shoes Bobby Freeman
❌ Error retrieving valence for Betty Lou Got A New Pair Of Shoes by Bobby Freeman: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Betty+Lou+Got+A+New+Pair+Of+Shoes+Bobby+Freeman&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Ramrod Duane Eddy His Twangy Guitar And The Rebels
❌ Error retrieving valence for Ramrod by Duane Eddy His Twangy Guitar And The Rebels: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Ramrod+Duane+Eddy+His+Twangy+Guitar+And+The+Rebels&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Chipmunk Song The Chipmunks With David Seville

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Chipmunk Song The Chipmunks With David Seville', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Philadelphia U.S.A. The Nu Tornados', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Lonely Teardrops Jackie Wilson', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Guess Things Happen That Way Johnny Cash And The Tennessee Two', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Green Mosquito The Tune Rockers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Look Who's Blue Don Gibson", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Cimarron (Roll On) Billy Vaughn And His Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for The Chipmunk Song by The Chipmunks With David Seville: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Chipmunk+Song+The+Chipmunks+With+David+Seville&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Philadelphia U.S.A. The Nu Tornados
❌ Error retrieving valence for Philadelphia U.S.A. by The Nu Tornados: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Philadelphia+U.S.A.+The+Nu+Tornados&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Lonely Teardrops Jackie Wilson
❌ Error retrieving valence for Lonely Teardrops by Jackie Wilson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Lonely+Teardrops+Jackie+Wilson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Guess Things Happen That Way Johnny Cash And The Tennessee Two
❌ Error retrieving valence for Guess Things Happen That Way by Johnny Cash And The Tennessee Two: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Guess+Things+Happen+That+Way+Johnny+Cash+And+The+Tennessee+Two&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Green Mosquito The Tune Rockers
❌ Error retrieving valence for The Green Mosquito by The Tune Rockers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Green+Mosquito+The+Tune+Rockers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Look Who's Blue Don Gibson
❌ Error retrieving valence for Look Who's Blue by Don Gibson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Look+Who%27s+Blue+Don+Gibson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Cimarron (Roll On) Billy Vaughn And His Orchestra
❌ Error retrieving valence for Cimarron (Roll On) by Billy Vaughn And His Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Cimarron+%28Roll+On%29+Billy+Vaughn+And+His+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Come On Let's Go Ritchie Valens

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Come On Let's Go Ritchie Valens", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'What Am I Living For Chuck Willis', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'For Your Precious Love Jerry Butler and The Impressions', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'No One But You (In My Heart) The Ames Brothers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Love You Most Of All Sam Cooke', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Dance Everyone Dance Betty Madigan', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Enchanted Island The Four Lads', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Come On Let's Go by Ritchie Valens: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Come+On+Let%27s+Go+Ritchie+Valens&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: What Am I Living For Chuck Willis
❌ Error retrieving valence for What Am I Living For by Chuck Willis: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=What+Am+I+Living+For+Chuck+Willis&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: For Your Precious Love Jerry Butler and The Impressions
❌ Error retrieving valence for For Your Precious Love by Jerry Butler and The Impressions: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=For+Your+Precious+Love+Jerry+Butler+and+The+Impressions&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: No One But You (In My Heart) The Ames Brothers
❌ Error retrieving valence for No One But You (In My Heart) by The Ames Brothers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=No+One+But+You+%28In+My+Heart%29+The+Ames+Brothers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Love You Most Of All Sam Cooke
❌ Error retrieving valence for Love You Most Of All by Sam Cooke: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Love+You+Most+Of+All+Sam+Cooke&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Dance Everyone Dance Betty Madigan
❌ Error retrieving valence for Dance Everyone Dance by Betty Madigan: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Dance+Everyone+Dance+Betty+Madigan&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Enchanted Island The Four Lads
❌ Error retrieving valence for Enchanted Island by The Four Lads: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Enchanted+Island+The+Four+Lads&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: You Cheated The Slades

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'You Cheated The Slades', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Sweet Little Rock And Roller Chuck Berry', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Give Myself A Party Don Gibson', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Mandolins In The Moonlight Perry Como', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Pledging My Love Roy Hamilton', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Leave Me Alone (Let Me Cry) Dicky Doo And The Don'ts", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for You Cheated by The Slades: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=You+Cheated+The+Slades&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Sweet Little Rock And Roller Chuck Berry
❌ Error retrieving valence for Sweet Little Rock And Roller by Chuck Berry: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Sweet+Little+Rock+And+Roller+Chuck+Berry&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Give Myself A Party Don Gibson
❌ Error retrieving valence for Give Myself A Party by Don Gibson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Give+Myself+A+Party+Don+Gibson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Mandolins In The Moonlight Perry Como
❌ Error retrieving valence for Mandolins In The Moonlight by Perry Como: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Mandolins+In+The+Moonlight+Perry+Como&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Pledging My Love Roy Hamilton
❌ Error retrieving valence for Pledging My Love by Roy Hamilton: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Pledging+My+Love+Roy+Hamilton&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Leave Me Alone (Let Me Cry) Dicky Doo And The Don'ts
❌ Error retrieving valence for Leave Me Alone (Let Me Cry) by Dicky Doo And The Don'ts: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Leave+Me+Alone+%28Let+Me+Cry%29+Dicky+Doo+And+The+Don%27ts&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Wizard Jimmie Rodgers

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Wizard Jimmie Rodgers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Donna Ritchie Valens', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Tunnel Of Love Doris Day', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'By The Light Of The Silvery Moon Jimmy Bowen with the Rhythm Orchids', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Do You Want To Dance Bobby Freeman', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'A Part Of Me Jimmy Clanton', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for The Wizard by Jimmie Rodgers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Wizard+Jimmie+Rodgers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Donna Ritchie Valens
❌ Error retrieving valence for Donna by Ritchie Valens: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Donna+Ritchie+Valens&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Tunnel Of Love Doris Day
❌ Error retrieving valence for Tunnel Of Love by Doris Day: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Tunnel+Of+Love+Doris+Day&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: By The Light Of The Silvery Moon Jimmy Bowen with the Rhythm Orchids
❌ Error retrieving valence for By The Light Of The Silvery Moon by Jimmy Bowen with the Rhythm Orchids: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=By+The+Light+Of+The+Silvery+Moon+Jimmy+Bowen+with+the+Rhythm+Orchids&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Do You Want To Dance Bobby Freeman
❌ Error retrieving valence for Do You Want To Dance by Bobby Freeman: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Do+You+Want+To+Dance+Bobby+Freeman&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: A Part Of Me Jimmy Clanton
❌ Error retrieving valence for A Part Of Me by Jimmy Clanton: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=A+Part+Of+Me+Jimmy+Clanton&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I Wish The Platters

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'I Wish The Platters', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Nine More Miles (The "Faster-Faster" Song) Georgie Young', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'My Happiness Connie Francis', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Endless Sleep Jody Reynolds', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Guaglione Perez Prado And His Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Teen Commandments Paul Anka-Geo. Hamilton IV-Johnny Nash', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for I Wish by The Platters: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I+Wish+The+Platters&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Nine More Miles (The "Faster-Faster" Song) Georgie Young
❌ Error retrieving valence for Nine More Miles (The "Faster-Faster" Song) by Georgie Young: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Nine+More+Miles+%28The+%22Faster-Faster%22+Song%29+Georgie+Young&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: My Happiness Connie Francis
❌ Error retrieving valence for My Happiness by Connie Francis: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=My+Happiness+Connie+Francis&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Endless Sleep Jody Reynolds
❌ Error retrieving valence for Endless Sleep by Jody Reynolds: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Endless+Sleep+Jody+Reynolds&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Guaglione Perez Prado And His Orchestra
❌ Error retrieving valence for Guaglione by Perez Prado And His Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Guaglione+Perez+Prado+And+His+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Teen Commandments Paul Anka-Geo. Hamilton IV-Johnny Nash
❌ Error retrieving valence for The Teen Commandments by Paul Anka-Geo. Hamilton IV-Johnny Nash: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Teen+Commandments+Paul+Anka-Geo.+Hamilton+IV-Johnny+Nash&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: 16 Candles The Crests

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': '16 Candles The Crests', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Sing Sing Sing Bernie Lowe Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Turvy II Cozy Cole', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'I Want To Be Happy Cha Cha Enoch Light & The Light Brigade', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Jealous Heart Tab Hunter', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'What Do I Care Johnny Cash', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Angel Baby Dean Martin', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for 16 Candles by The Crests: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=16+Candles+The+Crests&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Sing Sing Sing Bernie Lowe Orchestra
❌ Error retrieving valence for Sing Sing Sing by Bernie Lowe Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Sing+Sing+Sing+Bernie+Lowe+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Turvy II Cozy Cole
❌ Error retrieving valence for Turvy II by Cozy Cole: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Turvy+II+Cozy+Cole&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I Want To Be Happy Cha Cha Enoch Light & The Light Brigade
❌ Error retrieving valence for I Want To Be Happy Cha Cha by Enoch Light & The Light Brigade: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I+Want+To+Be+Happy+Cha+Cha+Enoch+Light+%26+The+Light+Brigade&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Jealous Heart Tab Hunter
❌ Error retrieving valence for Jealous Heart by Tab Hunter: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Jealous+Heart+Tab+Hunter&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: What Do I Care Johnny Cash
❌ Error retrieving valence for What Do I Care by Johnny Cash: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=What+Do+I+Care+Johnny+Cash&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Angel Baby Dean Martin
❌ Error retrieving valence for Angel Baby by Dean Martin: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Angel+Baby+Dean+Martin&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Kathy-O The Diamonds

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Kathy-O The Diamonds', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Don't Ask Me Why Elvis Presley With The Jordanaires", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Freeze Tony And Joe', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Hula Hoop Song Georgia Gibbs', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Cerveza Boots Brown And His Blockbusters', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "That's How Much I Love You Pat Boone", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Kathy-O by The Diamonds: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Kathy-O+The+Diamonds&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Don't Ask Me Why Elvis Presley With The Jordanaires
❌ Error retrieving valence for Don't Ask Me Why by Elvis Presley With The Jordanaires: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Don%27t+Ask+Me+Why+Elvis+Presley+With+The+Jordanaires&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Freeze Tony And Joe
❌ Error retrieving valence for The Freeze by Tony And Joe: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Freeze+Tony+And+Joe&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Hula Hoop Song Georgia Gibbs
❌ Error retrieving valence for The Hula Hoop Song by Georgia Gibbs: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Hula+Hoop+Song+Georgia+Gibbs&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Cerveza Boots Brown And His Blockbusters
❌ Error retrieving valence for Cerveza by Boots Brown And His Blockbusters: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Cerveza+Boots+Brown+And+His+Blockbusters&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: That's How Much I Love You Pat Boone
❌ Error retrieving valence for That's How Much I Love You by Pat Boone: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=That%27s+How+Much+I+Love+You+Pat+Boone&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Manhattan Spiritual Reg Owen & His Orchestra

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Manhattan Spiritual Reg Owen & His Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Blue Ribbon Baby Tommy Sands And The Raiders', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Big Bopper's Wedding Big Bopper", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Peek-A-Boo The Cadillacs', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Nobody But You Dee Clark', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Love Of My Life The Everly Brothers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Manhattan Spiritual by Reg Owen & His Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Manhattan+Spiritual+Reg+Owen+%26+His+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Blue Ribbon Baby Tommy Sands And The Raiders
❌ Error retrieving valence for Blue Ribbon Baby by Tommy Sands And The Raiders: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Blue+Ribbon+Baby+Tommy+Sands+And+The+Raiders&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Big Bopper's Wedding Big Bopper
❌ Error retrieving valence for Big Bopper's Wedding by Big Bopper: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Big+Bopper%27s+Wedding+Big+Bopper&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Peek-A-Boo The Cadillacs
❌ Error retrieving valence for Peek-A-Boo by The Cadillacs: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Peek-A-Boo+The+Cadillacs&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Nobody But You Dee Clark
❌ Error retrieving valence for Nobody But You by Dee Clark: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Nobody+But+You+Dee+Clark&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Love Of My Life The Everly Brothers
❌ Error retrieving valence for Love Of My Life by The Everly Brothers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Love+Of+My+Life+The+Everly+Brothers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: C'mon Everybody Eddie Cochran

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "C'mon Everybody Eddie Cochran", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Diary Neil Sedaka', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Wedding June Valli', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Chariot Rock The Champs', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'When I Grow Too Old To Dream Ed Townsend', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Ballad Of Thunder Road Robert Mitchum', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for C'mon Everybody by Eddie Cochran: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=C%27mon+Everybody+Eddie+Cochran&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Diary Neil Sedaka
❌ Error retrieving valence for The Diary by Neil Sedaka: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Diary+Neil+Sedaka&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Wedding June Valli
❌ Error retrieving valence for The Wedding by June Valli: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Wedding+June+Valli&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Chariot Rock The Champs
❌ Error retrieving valence for Chariot Rock by The Champs: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Chariot+Rock+The+Champs&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: When I Grow Too Old To Dream Ed Townsend
❌ Error retrieving valence for When I Grow Too Old To Dream by Ed Townsend: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=When+I+Grow+Too+Old+To+Dream+Ed+Townsend&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Ballad Of Thunder Road Robert Mitchum
❌ Error retrieving valence for The Ballad Of Thunder Road by Robert Mitchum: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Ballad+Of+Thunder+Road+Robert+Mitchum&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Need Your Love Bobby Freeman

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Need Your Love Bobby Freeman', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Blue Boy Jim Reeves', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Light Of Love Peggy Lee', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Purple People Eater Sheb Wooley', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Come What May Clyde McPhatter', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Gotta Have Rain Eydie Gorme', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Need Your Love by Bobby Freeman: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Need+Your+Love+Bobby+Freeman&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Blue Boy Jim Reeves
❌ Error retrieving valence for Blue Boy by Jim Reeves: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Blue+Boy+Jim+Reeves&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Light Of Love Peggy Lee
❌ Error retrieving valence for Light Of Love by Peggy Lee: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Light+Of+Love+Peggy+Lee&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Purple People Eater Sheb Wooley
❌ Error retrieving valence for The Purple People Eater by Sheb Wooley: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Purple+People+Eater+Sheb+Wooley&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Come What May Clyde McPhatter
❌ Error retrieving valence for Come What May by Clyde McPhatter: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Come+What+May+Clyde+McPhatter&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Gotta Have Rain Eydie Gorme
❌ Error retrieving valence for Gotta Have Rain by Eydie Gorme: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Gotta+Have+Rain+Eydie+Gorme&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I Cried A Tear LaVern Baker

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'I Cried A Tear LaVern Baker', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Secretly Jimmie Rodgers', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Alone With You Faron Young', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The Hula Hoop Song Teresa Brewer', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Hoopa Hoola Betty Johnson', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'My Life Chuck Willis', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Padre Toni Arden', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for I Cried A Tear by LaVern Baker: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I+Cried+A+Tear+LaVern+Baker&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Secretly Jimmie Rodgers
❌ Error retrieving valence for Secretly by Jimmie Rodgers: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Secretly+Jimmie+Rodgers&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Alone With You Faron Young
❌ Error retrieving valence for Alone With You by Faron Young: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Alone+With+You+Faron+Young&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The Hula Hoop Song Teresa Brewer
❌ Error retrieving valence for The Hula Hoop Song by Teresa Brewer: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+Hula+Hoop+Song+Teresa+Brewer&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Hoopa Hoola Betty Johnson
❌ Error retrieving valence for Hoopa Hoola by Betty Johnson: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Hoopa+Hoola+Betty+Johnson&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: My Life Chuck Willis
❌ Error retrieving valence for My Life by Chuck Willis: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=My+Life+Chuck+Willis&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Padre Toni Arden
❌ Error retrieving valence for Padre by Toni Arden: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Padre+Toni+Arden&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Crazy Eyes For You Bobby Hamilton

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Crazy Eyes For You Bobby Hamilton', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'No Chemise Please Gerry Granahan', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Break-Up Jerry Lee Lewis And His Pumping Piano', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': '¿Dònde Està Santa Claus? (Where Is Santa Claus?) Augie Rios', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Over The Weekend The Playboys', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Go Chase A Moonbeam Jerry Vale', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Crazy Eyes For You by Bobby Hamilton: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Crazy+Eyes+For+You+Bobby+Hamilton&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: No Chemise Please Gerry Granahan
❌ Error retrieving valence for No Chemise Please by Gerry Granahan: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=No+Chemise+Please+Gerry+Granahan&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Break-Up Jerry Lee Lewis And His Pumping Piano
❌ Error retrieving valence for Break-Up by Jerry Lee Lewis And His Pumping Piano: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Break-Up+Jerry+Lee+Lewis+And+His+Pumping+Piano&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: ¿Dònde Està Santa Claus? (Where Is Santa Claus?) Augie Rios
❌ Error retrieving valence for ¿Dònde Està Santa Claus? (Where Is Santa Claus?) by Augie Rios: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=%C2%BFD%C3%B2nde+Est%C3%A0+Santa+Claus%3F+%28Where+Is+Santa+Claus%3F%29+Augie+Rios&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Over The Weekend The Playboys
❌ Error retrieving valence for Over The Weekend by The Playboys: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Over+The+Weekend+The+Playboys&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Go Chase A Moonbeam Jerry Vale
❌ Error retrieving valence for Go Chase A Moonbeam by Jerry Vale: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Go+Chase+A+Moonbeam+Jerry+Vale&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Goodbye Baby Jack Scott

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Goodbye Baby Jack Scott', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Leroy Jack Scott', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': '(All of a Sudden) My Heart Sings Paul Anka', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Hey Girl - Hey Boy Oscar McLollie and Jeanette Baker', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Stagger Lee Lloyd Price', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Cinderella The Four Preps', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Intermission Riff Bernie Lowe Orchestra', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Goodbye Baby by Jack Scott: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Goodbye+Baby+Jack+Scott&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Leroy Jack Scott
❌ Error retrieving valence for Leroy by Jack Scott: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Leroy+Jack+Scott&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: (All of a Sudden) My Heart Sings Paul Anka
❌ Error retrieving valence for (All of a Sudden) My Heart Sings by Paul Anka: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=%28All+of+a+Sudden%29+My+Heart+Sings+Paul+Anka&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Hey Girl - Hey Boy Oscar McLollie and Jeanette Baker
❌ Error retrieving valence for Hey Girl - Hey Boy by Oscar McLollie and Jeanette Baker: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Hey+Girl+-+Hey+Boy+Oscar+McLollie+and+Jeanette+Baker&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Stagger Lee Lloyd Price
❌ Error retrieving valence for Stagger Lee by Lloyd Price: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Stagger+Lee+Lloyd+Price&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Cinderella The Four Preps
❌ Error retrieving valence for Cinderella by The Four Preps: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Cinderella+The+Four+Preps&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Intermission Riff Bernie Lowe Orchestra

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Jingle Bell Rock Bobby Helms', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "It's Just About Time Johnny Cash And The Tennessee Two", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Midnight Paul Anka', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'The All American Boy Bill Parsons', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Just Young Andy Rose', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Intermission Riff by Bernie Lowe Orchestra: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Intermission+Riff+Bernie+Lowe+Orchestra&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Jingle Bell Rock Bobby Helms
❌ Error retrieving valence for Jingle Bell Rock by Bobby Helms: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Jingle+Bell+Rock+Bobby+Helms&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: It's Just About Time Johnny Cash And The Tennessee Two
❌ Error retrieving valence for It's Just About Time by Johnny Cash And The Tennessee Two: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=It%27s+Just+About+Time+Johnny+Cash+And+The+Tennessee+Two&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Midnight Paul Anka
❌ Error retrieving valence for Midnight by Paul Anka: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Midnight+Paul+Anka&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: The All American Boy Bill Parsons
❌ Error retrieving valence for The All American Boy by Bill Parsons: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=The+All+American+Boy+Bill+Parsons&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Just Young Andy Rose
❌ Error retrieving valence for Just Young by Andy Rose: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Just+Young+Andy+Rose&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Return To Me Dean Martin

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Return To Me Dean Martin', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Count Every Star The Rivieras', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Happy Years The Diamonds', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'When Will I Know George Hamilton IV', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'I Wonder Why Dion & The Belmonts', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Please Don't Do It Dale Wright And The Wright Guys With the Dons", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Return To Me by Dean Martin: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Return+To+Me+Dean+Martin&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Count Every Star The Rivieras
❌ Error retrieving valence for Count Every Star by The Rivieras: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Count+Every+Star+The+Rivieras&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Happy Years The Diamonds
❌ Error retrieving valence for Happy Years by The Diamonds: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Happy+Years+The+Diamonds&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: When Will I Know George Hamilton IV
❌ Error retrieving valence for When Will I Know by George Hamilton IV: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=When+Will+I+Know+George+Hamilton+IV&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: I Wonder Why Dion & The Belmonts
❌ Error retrieving valence for I Wonder Why by Dion & The Belmonts: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=I+Wonder+Why+Dion+%26+The+Belmonts&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Please Don't Do It Dale Wright And The Wright Guys With the Dons
❌ Error retrieving valence for Please Don't Do It by Dale Wright And The Wright Guys With the Dons: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Please+Don%27t+Do+It+Dale+Wright+And+The+Wright+Guys+With+the+Dons&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Try Me James Brown And The Famous Flames

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Try Me James Brown And The Famous Flames', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': 'Baubles Bangles And Beads The Kirby Stone Four', 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/search with Params: {'q': "Let's Go Steady For The Summer The Three G's", 'limit': 1, 'offset': 0, 'type': 'track', 'market': None} returned 400 due to Only valid bearer authentication supported

❌ Error retrieving valence for Try Me by James Brown And The Famous Flames: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Try+Me+James+Brown+And+The+Famous+Flames&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Baubles Bangles And Beads The Kirby Stone Four
❌ Error retrieving valence for Baubles Bangles And Beads by The Kirby Stone Four: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Baubles+Bangles+And+Beads+The+Kirby+Stone+Four&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: Let's Go Steady For The Summer The Three G's
❌ Error retrieving valence for Let's Go Steady For The Summer by The Three G's: http status: 400, code: -1 - https://api.spotify.com/v1/search?q=Let%27s+Go+Steady+For+The+Summer+The+Three+G%27s&limit=1&offset=0&type=track:
 Only valid bearer authentication supported, reason: None
Searching for: City Lights Ray Price

KeyboardInterrupt:

In [7]:
import spotipy
import requests
import pandas as pd
import time
from spotipy.oauth2 import SpotifyClientCredentials
import base64

# Your CSV file path
file_path = "/Users/inqsoncharoen/Documents/RStudio Module/yearly_billboard_chart.csv"
df = pd.read_csv(file_path)

# Your Spotify API credentials
SPOTIPY_CLIENT_ID = "572eb4f3685b49349cbd2517ac8c064e"
SPOTIPY_CLIENT_SECRET = "0e6ba40bf0e74257a939dabfb2019b9d"

# Manually obtain an access token
def get_access_token(client_id, client_secret):
    url = "https://accounts.spotify.com/api/token"
    headers = {
        "Authorization": "Basic " + base64.b64encode(f"{client_id}:{client_secret}".encode()).decode(),
        "Content-Type": "application/x-www-form-urlencoded",
    }
    data = {"grant_type": "client_credentials"}

    response = requests.post(url, headers=headers, data=data)
    
    if response.status_code == 200:
        return response.json().get("access_token")
    else:
        print(f"❌ Error: {response.status_code}, Response: {response.json()}")
        return None

# Get token
access_token = get_access_token(SPOTIPY_CLIENT_ID, SPOTIPY_CLIENT_SECRET)

# Initialize Spotipy client with manually set token
sp = spotipy.Spotify(auth=access_token)

# Function to get valence
# def get_valence(song, artist):
#     try:
#         query = f"{song} {artist}"
#         results = sp.search(q=query, type="track", limit=1)

#         if results['tracks']['items']:
#             track_id = results['tracks']['items'][0]['id']
#             features = sp.audio_features(track_id)

#             if features and features[0]:  # Check if features exist
#                 return features[0].get('valence', None)
#             else:
#                 print(f"⚠️ No valence data for {song} by {artist}")
#                 return None
#     except Exception as e:
#         print(f"❌ Error retrieving valence for {song} by {artist}: {e}")
#     return None

def get_valence(song, artist):
    try:
        query = f"{song} {artist}"
        results = sp.search(q=query, type="track", limit=1)

        if not results['tracks']['items']:  # If no results found, skip
            print(f"⚠️ Skipping: No results for {song} by {artist}")
            return None

        track_id = results['tracks']['items'][0]['id']
        features = sp.audio_features(track_id)

        if features and features[0]:  # Check if valence exists
            return features[0].get('valence', None)
        else:
            print(f"⚠️ Skipping: No valence data for {song} by {artist}")
            return None
    except Exception as e:
        print(f"❌ Error retrieving valence for {song} by {artist}: {e}")
        return None


# Apply valence function to each row in DataFrame
df['valence'] = df.apply(lambda row: get_valence(row['song'], row['artist']), axis=1)

# Save updated CSV
output_file = "yearly_billboard_chart_with_valence.csv"
df.to_csv(output_file, index=False)

print(f"✅ Updated CSV saved as {output_file}")

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=07GtDOCxmye5KDWsTSACPk with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2tvt5K7y1gndmCgtIoLo1f with Params: {} returned 403 due to None

❌ Error retrieving valence for Chantilly Lace by Big Bopper: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=07GtDOCxmye5KDWsTSACPk:
 None, reason: None
❌ Error retrieving valence for It's All In The Game by Tommy Edwards: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2tvt5K7y1gndmCgtIoLo1f:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5sdZEmlwDJpISfCjyCneHi with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2ZCkqAo0tzzCVOth7ityh5 with Params: {} returned 403 due to None

❌ Error retrieving valence for Rock-in Robin by Bobby Day: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5sdZEmlwDJpISfCjyCneHi:
 None, reason: None
❌ Error retrieving valence for Bird Dog by The Everly Brothers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2ZCkqAo0tzzCVOth7ityh5:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3KVII1yBwfwuNQLZXma0oS with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=67eLX8pb0aEvXWGQTpfRzf with Params: {} returned 403 due to None

❌ Error retrieving valence for Topsy II by Cozy Cole: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3KVII1yBwfwuNQLZXma0oS:
 None, reason: None
❌ Error retrieving valence for Little Star by The Elegants: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=67eLX8pb0aEvXWGQTpfRzf:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1xVOttVNT27FBTD8iHjOfU with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2ZMBEnxCyfYVjOrly55uMm with Params: {} returned 403 due to None

❌ Error retrieving valence for It's Only Make Believe by Conway Twitty: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1xVOttVNT27FBTD8iHjOfU:
 None, reason: None
❌ Error retrieving valence for Tears On My Pillow by Little Anthony And The Imperials: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2ZMBEnxCyfYVjOrly55uMm:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3QWUoUlkbCJPAD0YhLjtLS with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1xjCGpAJVRAECqs5Pt6Gw1 with Params: {} returned 403 due to None

❌ Error retrieving valence for Tea For Two Cha Cha by The Tommy Dorsey Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3QWUoUlkbCJPAD0YhLjtLS:
 None, reason: None
❌ Error retrieving valence for Susie Darlin' by Robin Luke: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1xjCGpAJVRAECqs5Pt6Gw1:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=197hpG6nCD06NzMa4fsNqE with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=79Iwb8D1mlLHzyrTzuA3cw with Params: {} returned 403 due to None

❌ Error retrieving valence for Nel Blu Dipinto Di Blu (Volaré) by Domenico Modugno: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=197hpG6nCD06NzMa4fsNqE:
 None, reason: None
❌ Error retrieving valence for The End by Earl Grant: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=79Iwb8D1mlLHzyrTzuA3cw:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5rivhNukBcqEX41XQDLYi9 with Params: {} returned 403 due to None

❌ Error retrieving valence for Tom Dooley by The Kingston Trio: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5rivhNukBcqEX41XQDLYi9:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1fDKsQrMYOTGHYgyIxycmM with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0ATAoiUA2Tn2kZ4582ces2 with Params: {} returned 403 due to None

❌ Error retrieving valence for Just A Dream by Jimmy Clanton And His Rockets: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1fDKsQrMYOTGHYgyIxycmM:
 None, reason: None
❌ Error retrieving valence for To Know Him, Is To Love Him by The Teddy Bears: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0ATAoiUA2Tn2kZ4582ces2:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3oAWTk92mZBxKBOKf8mR5v with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0aVMdNotlKqTs5eVAomnBw with Params: {} returned 403 due to None

❌ Error retrieving valence for Summertime Blues by Eddie Cochran: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3oAWTk92mZBxKBOKf8mR5v:
 None, reason: None
❌ Error retrieving valence for Near You by Roger Williams: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0aVMdNotlKqTs5eVAomnBw:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3ZyJfbh2Y9y15f45qY1pDJ with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2IqRdttvMd4Kjw4Uc7bXNN with Params: {} returned 403 due to None

❌ Error retrieving valence for Born Too Late by Poni-Tails: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3ZyJfbh2Y9y15f45qY1pDJ:
 None, reason: None
❌ Error retrieving valence for My True Love by Jack Scott: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2IqRdttvMd4Kjw4Uc7bXNN:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1BbZJplex0pifLjhuhoaK5 with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4FrMb1ckGBrhARbHySQKx5 with Params: {} returned 403 due to None

❌ Error retrieving valence for Patricia by Perez Prado And His Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1BbZJplex0pifLjhuhoaK5:
 None, reason: None
❌ Error retrieving valence for Devoted To You by The Everly Brothers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4FrMb1ckGBrhARbHySQKx5:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1asCFshazteZOYJ6gqv0Fj with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3gRfSnvdHjS7aW3iTWZrO2 with Params: {} returned 403 due to None

❌ Error retrieving valence for I Got A Feeling by Ricky Nelson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1asCFshazteZOYJ6gqv0Fj:
 None, reason: None
❌ Error retrieving valence for How The Time Flies by Jerry Wallace: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3gRfSnvdHjS7aW3iTWZrO2:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4CTPlWqBheq3LKgyA7xlPu with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3iYPe12BAZCKoqeQkloxGJ with Params: {} returned 403 due to None

❌ Error retrieving valence for The Day The Rains Came by Jane Morgan: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4CTPlWqBheq3LKgyA7xlPu:
 None, reason: None
❌ Error retrieving valence for Queen Of The Hop by Bobby Darin: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3iYPe12BAZCKoqeQkloxGJ:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0SsYlkXxZ5vkWOTsKxMfMz with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3Pm8SkXgrpRysOrQStZNbL with Params: {} returned 403 due to None

❌ Error retrieving valence for Lonesome Town by Ricky Nelson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0SsYlkXxZ5vkWOTsKxMfMz:
 None, reason: None
❌ Error retrieving valence for Pussy Cat by The Ames Brothers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3Pm8SkXgrpRysOrQStZNbL:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7DiVCf2QOi4XbyR9SXs0UV with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1LovgLdzrG2jawiAEy46Nj with Params: {} returned 403 due to None

❌ Error retrieving valence for Mexican Hat Rock by The Applejacks: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7DiVCf2QOi4XbyR9SXs0UV:
 None, reason: None
❌ Error retrieving valence for You Cheated by The Shields: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1LovgLdzrG2jawiAEy46Nj:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5ayybTSXNwcarDtxQKqvWX with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1ohTeu24SfPoEit2x68BGH with Params: {} returned 403 due to None

❌ Error retrieving valence for Poor Little Fool by Ricky Nelson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5ayybTSXNwcarDtxQKqvWX:
 None, reason: None
❌ Error retrieving valence for Western Movies by The Olympics: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1ohTeu24SfPoEit2x68BGH:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6Amt95aUoMeEFiI7K3CtgG with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=67j5dFhlLv10REcTogd17o with Params: {} returned 403 due to None

❌ Error retrieving valence for There Goes My Heart by Joni James: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6Amt95aUoMeEFiI7K3CtgG:
 None, reason: None
❌ Error retrieving valence for Call Me by Johnny Mathis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=67j5dFhlLv10REcTogd17o:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2CeqxyOZEyiL6pTDYZ9gPH with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6QfGyzfwf7dm38Tmf49BpC with Params: {} returned 403 due to None

❌ Error retrieving valence for Fever by Peggy Lee: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2CeqxyOZEyiL6pTDYZ9gPH:
 None, reason: None
❌ Error retrieving valence for Everybody Loves A Lover by Doris Day: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6QfGyzfwf7dm38Tmf49BpC:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=659zBLfvlpLiNIZwbnoacH with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6HBgCYResmsdmOufyHVoNB with Params: {} returned 403 due to None

❌ Error retrieving valence for Are You Really Mine by Jimmie Rodgers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=659zBLfvlpLiNIZwbnoacH:
 None, reason: None
❌ Error retrieving valence for A Lover's Question by Clyde McPhatter: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6HBgCYResmsdmOufyHVoNB:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2RE4t6rX2Wcl2igB8MIOr4 with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0KM3fzzUBVW0vW7RmFh28v with Params: {} returned 403 due to None

❌ Error retrieving valence for Somebody Touched Me by Buddy Knox with the Rhythm Orchids: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2RE4t6rX2Wcl2igB8MIOr4:
 None, reason: None
❌ Error retrieving valence for Stupid Cupid by Connie Francis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0KM3fzzUBVW0vW7RmFh28v:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=49f1yPA6sXG9p893m0rgvp with Params: {} returned 403 due to None

❌ Error retrieving valence for Forget Me Not by Kalin Twins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=49f1yPA6sXG9p893m0rgvp:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6CZ6IeSfdqFPDk4uQn2Qlc with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3xkHsmpQCBMytMJNiDf3Ii with Params: {} returned 403 due to None

❌ Error retrieving valence for No One Knows by Dion & The Belmonts: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6CZ6IeSfdqFPDk4uQn2Qlc:
 None, reason: None
❌ Error retrieving valence for Hideaway by The Four Esquires: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3xkHsmpQCBMytMJNiDf3Ii:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3bNEy5u3HrAmOln2FiPcYD with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4dHj1lNBs6aWDiki4LXj8W with Params: {} returned 403 due to None

❌ Error retrieving valence for Win Your Love For Me by Sam Cooke: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3bNEy5u3HrAmOln2FiPcYD:
 None, reason: None
❌ Error retrieving valence for Beep Beep by The Playmates: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4dHj1lNBs6aWDiki4LXj8W:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2MufD7ORiUzuuBoRY5zoDe with Params: {} returned 403 due to None

❌ Error retrieving valence for Poor Boy by The Royaltones: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2MufD7ORiUzuuBoRY5zoDe:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4NCZEnM4tq2MazaFURJxWY with Params: {} returned 403 due to None

❌ Error retrieving valence for Firefly by Tony Bennett: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4NCZEnM4tq2MazaFURJxWY:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=50kRAxTeQ6r6EvWRlFp9pf with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3gGFiN3J8zXW3aqBbER4GT with Params: {} returned 403 due to None

❌ Error retrieving valence for Ginger Bread by Frankie Avalon: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=50kRAxTeQ6r6EvWRlFp9pf:
 None, reason: None
❌ Error retrieving valence for Ten Commandments Of Love by Harvey & The Moonglows: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3gGFiN3J8zXW3aqBbER4GT:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6NWKlkSFWP2Et2cEOpCbPY with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3XAH5ln2QXNrxyHEZJQBM5 with Params: {} returned 403 due to None

❌ Error retrieving valence for Volare (Nel Blu Dipinto Di Blu) by Dean Martin: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6NWKlkSFWP2Et2cEOpCbPY:
 None, reason: None
❌ Error retrieving valence for Need You by Donnie Owens: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3XAH5ln2QXNrxyHEZJQBM5:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0IDFXLMABcj61OKI3L05A0 with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4ToAe9XCKjFGin2Qfswwis with Params: {} returned 403 due to None

❌ Error retrieving valence for I Got Stung by Elvis Presley: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0IDFXLMABcj61OKI3L05A0:
 None, reason: None
❌ Error retrieving valence for Willie And The Hand Jive by The Johnny Otis Show: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4ToAe9XCKjFGin2Qfswwis:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=36CvDUCDMDbp3dZidKxTds with Params: {} returned 403 due to None

❌ Error retrieving valence for Itchy Twitchy Feeling by Bobby Hendricks: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=36CvDUCDMDbp3dZidKxTds:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2Y6H8Dzgy6XR7lzOQGPMTa with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6uuP61uWBQXeZG1kMZzr2B with Params: {} returned 403 due to None

❌ Error retrieving valence for One Night by Elvis Presley: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2Y6H8Dzgy6XR7lzOQGPMTa:
 None, reason: None
❌ Error retrieving valence for I'll Wait For You by Frankie Avalon: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6uuP61uWBQXeZG1kMZzr2B:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0UvACIi4eBEDGvk1A23wmQ with Params: {} returned 403 due to None

❌ Error retrieving valence for Problems by The Everly Brothers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0UvACIi4eBEDGvk1A23wmQ:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=24vZ7MPPD3nDR79JdAaMcy with Params: {} returned 403 due to None

❌ Error retrieving valence for The Secret by Gordon MacRae: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=24vZ7MPPD3nDR79JdAaMcy:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=22SaoTU5eut0RiB3nPuiUh with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5k6fSva9tzMnz5KYkvGcsI with Params: {} returned 403 due to None

❌ Error retrieving valence for Love Is All We Need by Tommy Edwards: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=22SaoTU5eut0RiB3nPuiUh:
 None, reason: None
❌ Error retrieving valence for Promise Me, Love by Andy Williams: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5k6fSva9tzMnz5KYkvGcsI:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3HZJ9BLBpDya4p71VfXSWp with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0rg9q7hg7uEfwT4HwmxHAY with Params: {} returned 403 due to None

❌ Error retrieving valence for When by Kalin Twins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3HZJ9BLBpDya4p71VfXSWp:
 None, reason: None
❌ Error retrieving valence for Treasure Of Your Love by Eileen Rodgers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0rg9q7hg7uEfwT4HwmxHAY:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6vJmVHXKBsnLpEdLVym5Ot with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=10g0Z3METFNjlkJZvQlDmb with Params: {} returned 403 due to None

❌ Error retrieving valence for Down The Aisle Of Love by The Quin-Tones: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6vJmVHXKBsnLpEdLVym5Ot:
 None, reason: None
❌ Error retrieving valence for Rebel-'rouser by Duane Eddy His Twangy Guitar And The Rebels: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=10g0Z3METFNjlkJZvQlDmb:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3gsR6howXi3YynMxLEZU63 with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=41ADUIxv4MkkWi7kgaZMrH with Params: {} returned 403 due to None

❌ Error retrieving valence for A Letter To An Angel by Jimmy Clanton: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3gsR6howXi3YynMxLEZU63:
 None, reason: None
❌ Error retrieving valence for Carol by Chuck Berry: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=41ADUIxv4MkkWi7kgaZMrH:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7LwnMxT8wkDJJM6BaMJczd with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5rJKnidWzOye1umcITPE6g with Params: {} returned 403 due to None

❌ Error retrieving valence for For My Good Fortune by Pat Boone: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7LwnMxT8wkDJJM6BaMJczd:
 None, reason: None
❌ Error retrieving valence for Cannonball by Duane Eddy His Twangy Guitar And The Rebels: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5rJKnidWzOye1umcITPE6g:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3bOkX6Yz6Pe4NByWzuJY6G with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=23F0g4UHkNq7rBfhqj87KG with Params: {} returned 403 due to None

❌ Error retrieving valence for If Dreams Came True by Pat Boone: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3bOkX6Yz6Pe4NByWzuJY6G:
 None, reason: None
❌ Error retrieving valence for She Was Only Seventeen (He Was One Year More) by Marty Robbins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=23F0g4UHkNq7rBfhqj87KG:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=40fD7ct05FvQHLdQTgJelG with Params: {} returned 403 due to None

❌ Error retrieving valence for Splish Splash by Bobby Darin: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=40fD7ct05FvQHLdQTgJelG:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=34biX2NWJlVfxTZfEqB17I with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4i0zefXopR6Fpu1cLjUp6o with Params: {} returned 403 due to None

❌ Error retrieving valence for Lazy Summer Night by The Four Preps: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=34biX2NWJlVfxTZfEqB17I:
 None, reason: None
❌ Error retrieving valence for Bimbombey by Jimmie Rodgers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4i0zefXopR6Fpu1cLjUp6o:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=27wSgJv4b9YPQXshu0YNRZ with Params: {} returned 403 due to None

❌ Error retrieving valence for One Summer Night by The Danleers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=27wSgJv4b9YPQXshu0YNRZ:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3KVII1yBwfwuNQLZXma0oS with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4oUmIFmLr63KWNDcxBK7x3 with Params: {} returned 403 due to None

❌ Error retrieving valence for Topsy I by Cozy Cole: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3KVII1yBwfwuNQLZXma0oS:
 None, reason: None
❌ Error retrieving valence for I'll Remember Tonight by Pat Boone: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4oUmIFmLr63KWNDcxBK7x3:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2vSxjnyrWrtxyfzO47EX6q with Params: {} returned 403 due to None

❌ Error retrieving valence for Smoke Gets In Your Eyes by The Platters: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2vSxjnyrWrtxyfzO47EX6q:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0siuuZOYLpvY4ArqFjfRDk with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=37Vct7oArn3tHN3XXCJJ7p with Params: {} returned 403 due to None

❌ Error retrieving valence for Walking Along by The Diamonds: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0siuuZOYLpvY4ArqFjfRDk:
 None, reason: None
❌ Error retrieving valence for Summertime, Summertime by The Jamies: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=37Vct7oArn3tHN3XXCJJ7p:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=76eNJQoJmN4mfsUW0q8HPv with Params: {} returned 403 due to None

❌ Error retrieving valence for A Certain Smile by Johnny Mathis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=76eNJQoJmN4mfsUW0q8HPv:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0VZWkRDVnVcCZIBhT2eGZG with Params: {} returned 403 due to None

❌ Error retrieving valence for The World Outside by The Four Coins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0VZWkRDVnVcCZIBhT2eGZG:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=32CVurlBxtEYQlDm3yzCLl with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4nebs5HFOKkmIpxndZLp55 with Params: {} returned 403 due to None

❌ Error retrieving valence for Hard Headed Woman by Elvis Presley With The Jordanaires: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=32CVurlBxtEYQlDm3yzCLl:
 None, reason: None
❌ Error retrieving valence for Moon Talk by Perry Como: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4nebs5HFOKkmIpxndZLp55:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0chQAQKCSKrhFfqj07rrva with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6pS2nLsZBUOrMaFMPvFVwM with Params: {} returned 403 due to None

❌ Error retrieving valence for That Old Black Magic by Louis Prima And Keely Smith: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0chQAQKCSKrhFfqj07rrva:
 None, reason: None
❌ Error retrieving valence for Whole Lotta Loving by Fats Domino: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6pS2nLsZBUOrMaFMPvFVwM:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2gr3pqL0pjdw5cwSg4QIIk with Params: {} returned 403 due to None

❌ Error retrieving valence for La-Do-Dada by Dale Hawkins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2gr3pqL0pjdw5cwSg4QIIk:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=53lU2JYbWKBC0nnegGptZX with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6aOxKTk3Dh08MGgnLv9862 with Params: {} returned 403 due to None

❌ Error retrieving valence for Put A Ring On My Finger by Les Paul And Mary Ford: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=53lU2JYbWKBC0nnegGptZX:
 None, reason: None
❌ Error retrieving valence for La Paloma by Billy Vaughn And His Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6aOxKTk3Dh08MGgnLv9862:
 None, reason: None
❌ Error retrieving valence for With Your Love by Jack Scott: HTTPSConnectionPool(host='api.spotify.com', port=443): Read timed out. (read timeout=5)

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=19qkesdHjvJEZztR8kFuY3 with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1BQ1iEiTtOVxWc2MAVSDS8 with Params: {} returned 403 due to None

❌ Error retrieving valence for Early In The Morning by The Rinky-Dinks: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=19qkesdHjvJEZztR8kFuY3:
 None, reason: None
❌ Error retrieving valence for Left Right Out Of Your Heart (Hi Lee Hi Lo Hi Lup Up Up) by Patti Page: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1BQ1iEiTtOVxWc2MAVSDS8:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1hytwCuTvurrHkJcX9IW1D with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4p4S9Z9xQk1ZAUy8Z16IJb with Params: {} returned 403 due to None

❌ Error retrieving valence for The Ways Of A Woman In Love by Johnny Cash And The Tennessee Two: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1hytwCuTvurrHkJcX9IW1D:
 None, reason: None
❌ Error retrieving valence for Non Dimenticar (Don't Forget) by Nat King Cole: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4p4S9Z9xQk1ZAUy8Z16IJb:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2NibOTZFFgdzjKEIOw3zAM with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4EWzX1rNaid4E8sULZd1UZ with Params: {} returned 403 due to None

❌ Error retrieving valence for Over And Over by Bobby Day: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2NibOTZFFgdzjKEIOw3zAM:
 None, reason: None
❌ Error retrieving valence for Come Closer To Me (Acercate Mas) by Nat King Cole: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4EWzX1rNaid4E8sULZd1UZ:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3RPVk2uXTxAVwfxlWr7UBV with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2zRPoNXXMJKnD9cZTZUPzI with Params: {} returned 403 due to None

❌ Error retrieving valence for The Mocking Bird by The Four Lads: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3RPVk2uXTxAVwfxlWr7UBV:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2CeK4FKsz6k1ftawMc3rbJ with Params: {} returned 403 due to None

❌ Error retrieving valence for The Day The Rains Came by Raymond Lefevre and His Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2zRPoNXXMJKnD9cZTZUPzI:
 None, reason: None
❌ Error retrieving valence for Yakety Yak by The Coasters: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2CeK4FKsz6k1ftawMc3rbJ:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3gd3Eu7AEqJC1wcNx8P8xg with Params: {} returned 403 due to None

❌ Error retrieving valence for This Little Girl's Gone Rockin' by Ruth Brown: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3gd3Eu7AEqJC1wcNx8P8xg:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=52kUUsziFTCejlF4q7O7l2 with Params: {} returned 403 due to None

❌ Error retrieving valence for Love Makes The World Go 'round by Perry Como: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=52kUUsziFTCejlF4q7O7l2:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3KmaAbepfIVA6VYFIUhRLe with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7lTpgbvsCct5aGapyNKSWp with Params: {} returned 403 due to None

❌ Error retrieving valence for The Blob by The Five Blobs: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3KmaAbepfIVA6VYFIUhRLe:
 None, reason: None
❌ Error retrieving valence for Mr. Success by Frank Sinatra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7lTpgbvsCct5aGapyNKSWp:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6dp3vxQ5UVsxD6N1mbPxjg with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=23R3NTnNUt1YktcDDTLcAd with Params: {} returned 403 due to None

❌ Error retrieving valence for Early In The Morning by Buddy Holly: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6dp3vxQ5UVsxD6N1mbPxjg:
 None, reason: None
❌ Error retrieving valence for Think It Over by The Crickets: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=23R3NTnNUt1YktcDDTLcAd:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5VAN7D9sq2lzzAm5MMqw5Q with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4xWohADqZ5oFXcFOiC10l4 with Params: {} returned 403 due to None

❌ Error retrieving valence for Fibbin' by Patti Page: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5VAN7D9sq2lzzAm5MMqw5Q:
 None, reason: None
❌ Error retrieving valence for Blue Blue Day by Don Gibson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4xWohADqZ5oFXcFOiC10l4:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5Ttwn2VJRE5cqj7SlyhieC with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1x631Q0tVKGGn78ztY4A2x with Params: {} returned 403 due to None

❌ Error retrieving valence for Baby Face by Little Richard: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5Ttwn2VJRE5cqj7SlyhieC:
 None, reason: None
❌ Error retrieving valence for Gee, But It's Lonely by Pat Boone: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1x631Q0tVKGGn78ztY4A2x:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=76CbOXTXJpDSKplGwgUHiB with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=121oskeJBhi1OvqHqydCSf with Params: {} returned 403 due to None

❌ Error retrieving valence for All Over Again by Johnny Cash: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=76CbOXTXJpDSKplGwgUHiB:
 None, reason: None
❌ Error retrieving valence for Fallin' by Connie Francis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=121oskeJBhi1OvqHqydCSf:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2u5DsuT4NJmujdoaexMwTB with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3dyWBUhFyj6qlRknmC2JLn with Params: {} returned 403 due to None

❌ Error retrieving valence for Gotta Travel On by Billy Grammer: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2u5DsuT4NJmujdoaexMwTB:
 None, reason: None
❌ Error retrieving valence for Betty Lou Got A New Pair Of Shoes by Bobby Freeman: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3dyWBUhFyj6qlRknmC2JLn:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5rJKnidWzOye1umcITPE6g with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=02NKMA9cIkq6VuBNu9q9Wf with Params: {} returned 403 due to None

❌ Error retrieving valence for Ramrod by Duane Eddy His Twangy Guitar And The Rebels: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5rJKnidWzOye1umcITPE6g:
 None, reason: None
❌ Error retrieving valence for The Chipmunk Song by The Chipmunks With David Seville: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=02NKMA9cIkq6VuBNu9q9Wf:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0MZq5dbqFQrvDFyl8ou7dm with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6TYR3IVgIwDK6ydc2EPEQq with Params: {} returned 403 due to None

❌ Error retrieving valence for Philadelphia U.S.A. by The Nu Tornados: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0MZq5dbqFQrvDFyl8ou7dm:
 None, reason: None
❌ Error retrieving valence for Lonely Teardrops by Jackie Wilson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6TYR3IVgIwDK6ydc2EPEQq:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0XmVkj183Ahgnfyn6A77TO with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4xnz7L9d5UHIRRqxzX3Can with Params: {} returned 403 due to None

❌ Error retrieving valence for Guess Things Happen That Way by Johnny Cash And The Tennessee Two: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0XmVkj183Ahgnfyn6A77TO:
 None, reason: None
❌ Error retrieving valence for The Green Mosquito by The Tune Rockers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4xnz7L9d5UHIRRqxzX3Can:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5SvpntrCSEeM6rwOwbO7tL with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3oR8vpy1HvSrqr2uZ5cX38 with Params: {} returned 403 due to None

❌ Error retrieving valence for Look Who's Blue by Don Gibson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5SvpntrCSEeM6rwOwbO7tL:
 None, reason: None
❌ Error retrieving valence for Cimarron (Roll On) by Billy Vaughn And His Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3oR8vpy1HvSrqr2uZ5cX38:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4cRfSR0QxDlXRHTKyEOu93 with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6eIEXINZt8rtgqEtOxP9ur with Params: {} returned 403 due to None

❌ Error retrieving valence for Come On, Let's Go by Ritchie Valens: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4cRfSR0QxDlXRHTKyEOu93:
 None, reason: None
❌ Error retrieving valence for What Am I Living For by Chuck Willis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6eIEXINZt8rtgqEtOxP9ur:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4vVFD4ZzlDZpjfxKsuQzz3 with Params: {} returned 403 due to None

❌ Error retrieving valence for For Your Precious Love by Jerry Butler and The Impressions: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4vVFD4ZzlDZpjfxKsuQzz3:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1SGvjfc85yzqKXsfKcCxn2 with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0nvzDz3CqEViJaqT2cuFuY with Params: {} returned 403 due to None

❌ Error retrieving valence for No One But You (In My Heart) by The Ames Brothers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1SGvjfc85yzqKXsfKcCxn2:
 None, reason: None
❌ Error retrieving valence for Love You Most Of All by Sam Cooke: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0nvzDz3CqEViJaqT2cuFuY:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1wA4m1zlaMCE6zDY7FwAdU with Params: {} returned 403 due to None

❌ Error retrieving valence for Dance Everyone Dance by Betty Madigan: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1wA4m1zlaMCE6zDY7FwAdU:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4JtUrtgn1J8PWpgOxeCUYc with Params: {} returned 403 due to None

❌ Error retrieving valence for Enchanted Island by The Four Lads: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4JtUrtgn1J8PWpgOxeCUYc:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2QrZsVjOlmIvMRSzPrAYyw with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5a38im3bvcPzWWIuMegbTe with Params: {} returned 403 due to None

❌ Error retrieving valence for You Cheated by The Slades: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2QrZsVjOlmIvMRSzPrAYyw:
 None, reason: None
❌ Error retrieving valence for Sweet Little Rock And Roller by Chuck Berry: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5a38im3bvcPzWWIuMegbTe:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7u514EtyvrUmFw7fipyHue with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7hgpTBrkmNjs4QFV7qTrhw with Params: {} returned 403 due to None

❌ Error retrieving valence for Give Myself A Party by Don Gibson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7u514EtyvrUmFw7fipyHue:
 None, reason: None
❌ Error retrieving valence for Mandolins In The Moonlight by Perry Como: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7hgpTBrkmNjs4QFV7qTrhw:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=00K7iE0TKUUJVRqMcOuFst with Params: {} returned 403 due to None

❌ Error retrieving valence for Pledging My Love by Roy Hamilton: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=00K7iE0TKUUJVRqMcOuFst:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4RFSGZqEPc3QY3z68gfRiD with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2KRejPhPZaxmDtUbVgOwNR with Params: {} returned 403 due to None

❌ Error retrieving valence for Leave Me Alone (Let Me Cry) by Dicky Doo And The Don'ts: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4RFSGZqEPc3QY3z68gfRiD:
 None, reason: None
❌ Error retrieving valence for The Wizard by Jimmie Rodgers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2KRejPhPZaxmDtUbVgOwNR:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0VE4ayVlGs5DBoqOdgJ0Zv with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4QDoRgdeUpUb08fDK2o9lh with Params: {} returned 403 due to None

❌ Error retrieving valence for Donna by Ritchie Valens: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0VE4ayVlGs5DBoqOdgJ0Zv:
 None, reason: None
❌ Error retrieving valence for Tunnel Of Love by Doris Day: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4QDoRgdeUpUb08fDK2o9lh:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=61HT9cyi4PeDYUw6vlskhi with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4wXPZBafMKbTtdOB7BVGcp with Params: {} returned 403 due to None

❌ Error retrieving valence for By The Light Of The Silvery Moon by Jimmy Bowen with the Rhythm Orchids: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=61HT9cyi4PeDYUw6vlskhi:
 None, reason: None
❌ Error retrieving valence for Do You Want To Dance by Bobby Freeman: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4wXPZBafMKbTtdOB7BVGcp:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3TeCzKlTPHU700TzO6TTGV with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=74ZHF7tNTd2MN2pyJCyi35 with Params: {} returned 403 due to None

❌ Error retrieving valence for A Part Of Me by Jimmy Clanton: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3TeCzKlTPHU700TzO6TTGV:
 None, reason: None
❌ Error retrieving valence for I Wish by The Platters: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=74ZHF7tNTd2MN2pyJCyi35:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1eIK074m2N2klVFCY6tyrw with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=50EXZCtLwYyFxiGV8v7SuS with Params: {} returned 403 due to None

❌ Error retrieving valence for Nine More Miles (The "Faster-Faster" Song) by Georgie Young: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1eIK074m2N2klVFCY6tyrw:
 None, reason: None
❌ Error retrieving valence for My Happiness by Connie Francis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=50EXZCtLwYyFxiGV8v7SuS:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=20UqPKVahgJuPzc0rMbSyU with Params: {} returned 403 due to None

❌ Error retrieving valence for Endless Sleep by Jody Reynolds: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=20UqPKVahgJuPzc0rMbSyU:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5DfSMvjGCWmcwyZZqMlNjV with Params: {} returned 403 due to None

❌ Error retrieving valence for Guaglione by Perez Prado And His Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5DfSMvjGCWmcwyZZqMlNjV:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1sK2h8TBn6nIiI1JbFSKDh with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3Timk4Wy8wnJDCfq6O7YDW with Params: {} returned 403 due to None

❌ Error retrieving valence for The Teen Commandments by Paul Anka-Geo. Hamilton IV-Johnny Nash: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1sK2h8TBn6nIiI1JbFSKDh:
 None, reason: None
❌ Error retrieving valence for 16 Candles by The Crests: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3Timk4Wy8wnJDCfq6O7YDW:
 None, reason: None

HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0T4b706qiJ87eBtHcgq9oH with Params: {} returned 403 due to None
HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7CvHHVzETJ6ZwdVF2RAcCw with Params: {} returned 403 due to None

❌ Error retrieving valence for Sing Sing Sing by Bernie Lowe Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0T4b706qiJ87eBtHcgq9oH:
 None, reason: None
❌ Error retrieving valence for Turvy II by Cozy Cole: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7CvHHVzETJ6ZwdVF2RAcCw:
 None, reason: None

WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2cLjF8w21xcXqKlJNayjsQ with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=251N57e0EOzksKEv3znylo with Params: {} returned 403 due to None

❌ Error retrieving valence for I Want To Be Happy Cha Cha by Enoch Light & The Light Brigade: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2cLjF8w21xcXqKlJNayjsQ:
 None, reason: None
❌ Error retrieving valence for Jealous Heart by Tab Hunter: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=251N57e0EOzksKEv3znylo:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=172tOpuxcdARN92RIFvZaq with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5DX3P3b7kv8266XyuA7fsS with Params: {} returned 403 due to None

❌ Error retrieving valence for What Do I Care by Johnny Cash: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=172tOpuxcdARN92RIFvZaq:
 None, reason: None
❌ Error retrieving valence for Angel Baby by Dean Martin: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5DX3P3b7kv8266XyuA7fsS:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3lQN1QZLf11UDabPaVPElk with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0nKb6gYFt0jgs6c2nmqvSm with Params: {} returned 403 due to None

❌ Error retrieving valence for Kathy-O by The Diamonds: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3lQN1QZLf11UDabPaVPElk:
 None, reason: None
❌ Error retrieving valence for Don't Ask Me Why by Elvis Presley With The Jordanaires: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0nKb6gYFt0jgs6c2nmqvSm:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1JqyY1N64SmuGES3xcijPD with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7hhKHntv1THPgEQLJzBUam with Params: {} returned 403 due to None

❌ Error retrieving valence for The Freeze by Tony And Joe: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1JqyY1N64SmuGES3xcijPD:
 None, reason: None
❌ Error retrieving valence for The Hula Hoop Song by Georgia Gibbs: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7hhKHntv1THPgEQLJzBUam:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5C576xZTXP04a3PwSxNn0H with Params: {} returned 403 due to None

❌ Error retrieving valence for Cerveza by Boots Brown And His Blockbusters: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5C576xZTXP04a3PwSxNn0H:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3AITyYJRMParI2UsWHHcCQ with Params: {} returned 403 due to None

❌ Error retrieving valence for That's How Much I Love You by Pat Boone: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3AITyYJRMParI2UsWHHcCQ:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5yH7ZZKsi127nbKgQ98IU1 with Params: {} returned 403 due to None

❌ Error retrieving valence for Manhattan Spiritual by Reg Owen & His Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5yH7ZZKsi127nbKgQ98IU1:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3cXfUXNlulkiaQB9k6V68t with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5ZWuiWcMTBohMTTfdD5qys with Params: {} returned 403 due to None

❌ Error retrieving valence for Blue Ribbon Baby by Tommy Sands And The Raiders: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3cXfUXNlulkiaQB9k6V68t:
 None, reason: None
❌ Error retrieving valence for Big Bopper's Wedding by Big Bopper: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5ZWuiWcMTBohMTTfdD5qys:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4YTRJpKvS8DLClLcxUx0wI with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5uVaMG4Ay6yaSRP0dMw5tV with Params: {} returned 403 due to None

❌ Error retrieving valence for Peek-A-Boo by The Cadillacs: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4YTRJpKvS8DLClLcxUx0wI:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5c8TEsBNmg5Hh1v9U7N538 with Params: {} returned 403 due to None

❌ Error retrieving valence for Nobody But You by Dee Clark: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5uVaMG4Ay6yaSRP0dMw5tV:
 None, reason: None
❌ Error retrieving valence for Love Of My Life by The Everly Brothers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5c8TEsBNmg5Hh1v9U7N538:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7ItZM6DMZE2m1X7yIaRxjq with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1dyEgbiT6hWeNnwhgKsCzu with Params: {} returned 403 due to None

❌ Error retrieving valence for C'mon Everybody by Eddie Cochran: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7ItZM6DMZE2m1X7yIaRxjq:
 None, reason: None
❌ Error retrieving valence for The Diary by Neil Sedaka: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1dyEgbiT6hWeNnwhgKsCzu:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6MT0BQfBUBzCaruu6xQlYx with Params: {} returned 403 due to None

❌ Error retrieving valence for The Wedding by June Valli: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6MT0BQfBUBzCaruu6xQlYx:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6XryacCjlrgV6EXlQbEJRx with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0ePDsEDDIPZNpbwRUEXKoX with Params: {} returned 403 due to None

❌ Error retrieving valence for Chariot Rock by The Champs: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6XryacCjlrgV6EXlQbEJRx:
 None, reason: None
❌ Error retrieving valence for When I Grow Too Old To Dream by Ed Townsend: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0ePDsEDDIPZNpbwRUEXKoX:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4CORfI5PJIhyMw8uWpDfKz with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0qhtWcLuY5g9dkFsbPwiVv with Params: {} returned 403 due to None

❌ Error retrieving valence for The Ballad Of Thunder Road by Robert Mitchum: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4CORfI5PJIhyMw8uWpDfKz:
 None, reason: None
❌ Error retrieving valence for Need Your Love by Bobby Freeman: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0qhtWcLuY5g9dkFsbPwiVv:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=05k40oRJ58mQBJSAz0FkLI with Params: {} returned 403 due to None

❌ Error retrieving valence for Blue Boy by Jim Reeves: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=05k40oRJ58mQBJSAz0FkLI:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=13ErpYVZ6DKoEHVr2kSI7B with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5kwNtCCPJSKGBRconqm57X with Params: {} returned 403 due to None

❌ Error retrieving valence for Light Of Love by Peggy Lee: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=13ErpYVZ6DKoEHVr2kSI7B:
 None, reason: None
❌ Error retrieving valence for The Purple People Eater by Sheb Wooley: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5kwNtCCPJSKGBRconqm57X:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4UgiNlKI2BrCmMhGnrYFze with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1sYhm4ybjVUX09GDwIwXfS with Params: {} returned 403 due to None

❌ Error retrieving valence for Come What May by Clyde McPhatter: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4UgiNlKI2BrCmMhGnrYFze:
 None, reason: None
❌ Error retrieving valence for Gotta Have Rain by Eydie Gorme: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1sYhm4ybjVUX09GDwIwXfS:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=28dTB69zJBpBIiDH32Jp1M with Params: {} returned 403 due to None

❌ Error retrieving valence for I Cried A Tear by LaVern Baker: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=28dTB69zJBpBIiDH32Jp1M:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=23fipgIcZ3WwaIM4mCnDSe with Params: {} returned 403 due to None

❌ Error retrieving valence for Secretly by Jimmie Rodgers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=23fipgIcZ3WwaIM4mCnDSe:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6jLTTNVVY4UxCSBZ2Z8qdR with Params: {} returned 403 due to None

❌ Error retrieving valence for Alone With You by Faron Young: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6jLTTNVVY4UxCSBZ2Z8qdR:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6sCqtqLg3bPF8S9tXbzU3m with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5AtjtBVeTSMDiyJS2kO7Wk with Params: {} returned 403 due to None

❌ Error retrieving valence for The Hula Hoop Song by Teresa Brewer: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6sCqtqLg3bPF8S9tXbzU3m:
 None, reason: None
❌ Error retrieving valence for Hoopa Hoola by Betty Johnson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5AtjtBVeTSMDiyJS2kO7Wk:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=12qI44KzCUYMPE9RoDS7GI with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0TwtbWM3QK3OWhyCFufsrI with Params: {} returned 403 due to None

❌ Error retrieving valence for My Life by Chuck Willis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=12qI44KzCUYMPE9RoDS7GI:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6zH4F42t7jlPsRGcxGbK9a with Params: {} returned 403 due to None

❌ Error retrieving valence for Padre by Toni Arden: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0TwtbWM3QK3OWhyCFufsrI:
 None, reason: None
❌ Error retrieving valence for Crazy Eyes For You by Bobby Hamilton: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6zH4F42t7jlPsRGcxGbK9a:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4EtE8UckEKuHKBYVbpOILM with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1y1GznxfeQyO7rZJSfdIcF with Params: {} returned 403 due to None

❌ Error retrieving valence for No Chemise, Please by Gerry Granahan: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4EtE8UckEKuHKBYVbpOILM:
 None, reason: None
❌ Error retrieving valence for Break-Up by Jerry Lee Lewis And His Pumping Piano: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1y1GznxfeQyO7rZJSfdIcF:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5MZE6vJIPYsAfVDB7QVmTX with Params: {} returned 403 due to None

❌ Error retrieving valence for ¿Dònde Està Santa Claus? (Where Is Santa Claus?) by Augie Rios: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5MZE6vJIPYsAfVDB7QVmTX:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2ANXqdHSALWGqMmLDoSr0G with Params: {} returned 403 due to None

❌ Error retrieving valence for Over The Weekend by The Playboys: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2ANXqdHSALWGqMmLDoSr0G:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4zkFeOZb1DkQgoP7F1zJNN with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4mqesBnOwDY6Aeoa401t8q with Params: {} returned 403 due to None

❌ Error retrieving valence for Go Chase A Moonbeam by Jerry Vale: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4zkFeOZb1DkQgoP7F1zJNN:
 None, reason: None
❌ Error retrieving valence for Goodbye Baby by Jack Scott: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4mqesBnOwDY6Aeoa401t8q:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1tPhhisY2EQI7M4YjWPuSl with Params: {} returned 403 due to None

❌ Error retrieving valence for Leroy by Jack Scott: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1tPhhisY2EQI7M4YjWPuSl:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0zKZqHPNUKjjhsUJHT06RZ with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=77HMOgvWpWmO65hJ2NV3OO with Params: {} returned 403 due to None

❌ Error retrieving valence for (All of a Sudden) My Heart Sings by Paul Anka: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0zKZqHPNUKjjhsUJHT06RZ:
 None, reason: None
❌ Error retrieving valence for Hey Girl - Hey Boy by Oscar McLollie and Jeanette Baker: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=77HMOgvWpWmO65hJ2NV3OO:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7qoaMWT3eRCKG1RN6dVuOY with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2pgFEUd7qK8fVyASICkglU with Params: {} returned 403 due to None

❌ Error retrieving valence for Stagger Lee by Lloyd Price: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7qoaMWT3eRCKG1RN6dVuOY:
 None, reason: None
❌ Error retrieving valence for Cinderella by The Four Preps: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2pgFEUd7qK8fVyASICkglU:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0BC19tWJKz5SoAXsThlpHX with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7vQbuQcyTflfCIOu3Uzzya with Params: {} returned 403 due to None

❌ Error retrieving valence for Intermission Riff by Bernie Lowe Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0BC19tWJKz5SoAXsThlpHX:
 None, reason: None
❌ Error retrieving valence for Jingle Bell Rock by Bobby Helms: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7vQbuQcyTflfCIOu3Uzzya:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=185RyaGfeQDqxLCw6LvI3R with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5lHDpxhJuWfNefd2IImNLi with Params: {} returned 403 due to None

❌ Error retrieving valence for It's Just About Time by Johnny Cash And The Tennessee Two: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=185RyaGfeQDqxLCw6LvI3R:
 None, reason: None
❌ Error retrieving valence for Midnight by Paul Anka: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5lHDpxhJuWfNefd2IImNLi:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2JXQ9QIe9TaaHpCt0mORyO with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7eJCaAPYsxRGHgXidNnmeJ with Params: {} returned 403 due to None

❌ Error retrieving valence for The All American Boy by Bill Parsons: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2JXQ9QIe9TaaHpCt0mORyO:
 None, reason: None
❌ Error retrieving valence for Just Young by Andy Rose: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7eJCaAPYsxRGHgXidNnmeJ:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6YAgmqaeo8Fm3pne8OJEBo with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0lDaLquROBu6XlWB9g7BP7 with Params: {} returned 403 due to None

❌ Error retrieving valence for Return To Me by Dean Martin: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6YAgmqaeo8Fm3pne8OJEBo:
 None, reason: None
❌ Error retrieving valence for Count Every Star by The Rivieras: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0lDaLquROBu6XlWB9g7BP7:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3nG72GXuVEXeey7YJtpEGd with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1h6Ih6Wndyk1WOEZw6pDhc with Params: {} returned 403 due to None

❌ Error retrieving valence for Happy Years by The Diamonds: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3nG72GXuVEXeey7YJtpEGd:
 None, reason: None
❌ Error retrieving valence for When Will I Know by George Hamilton IV: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1h6Ih6Wndyk1WOEZw6pDhc:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7vAw4LLIms6X8ZHcbtoazz with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2b8XyVHX2UxxiGyUsAMQRf with Params: {} returned 403 due to None

❌ Error retrieving valence for I Wonder Why by Dion & The Belmonts: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7vAw4LLIms6X8ZHcbtoazz:
 None, reason: None
❌ Error retrieving valence for Please Don't Do It by Dale Wright And The Wright Guys With the Dons: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2b8XyVHX2UxxiGyUsAMQRf:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7bFfjakySYhojqSPrAPtc3 with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5tZEhidEi4us9UsnIlRKiL with Params: {} returned 403 due to None

❌ Error retrieving valence for Try Me by James Brown And The Famous Flames: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7bFfjakySYhojqSPrAPtc3:
 None, reason: None
❌ Error retrieving valence for Baubles, Bangles And Beads by The Kirby Stone Four: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5tZEhidEi4us9UsnIlRKiL:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6c4MQr28fWE4YxRUCSs55K with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=62RfCZpT2zfBHRXD8yp2WV with Params: {} returned 403 due to None

❌ Error retrieving valence for Let's Go Steady For The Summer by The Three G's: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6c4MQr28fWE4YxRUCSs55K:
 None, reason: None
❌ Error retrieving valence for City Lights by Ray Price: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=62RfCZpT2zfBHRXD8yp2WV:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5uV5UT7DFkdpJODYHBO0Bc with Params: {} returned 403 due to None

❌ Error retrieving valence for Come Prima by Tony Dallara: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5uV5UT7DFkdpJODYHBO0Bc:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6FkZExe98I09sykw0l55Iu with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2px21n5ieOpOeeFuqmHCsa with Params: {} returned 403 due to None

❌ Error retrieving valence for The World Outside by The Four Aces: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6FkZExe98I09sykw0l55Iu:
 None, reason: None
❌ Error retrieving valence for Real Wild Child by Ivan: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2px21n5ieOpOeeFuqmHCsa:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5WoYLgoJekr3ZL9uJcHXgJ with Params: {} returned 403 due to None

❌ Error retrieving valence for The Little Drummer Boy by The Harry Simeone Chorale: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5WoYLgoJekr3ZL9uJcHXgJ:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2hECDE2rtiNWCjxviTO5W4 with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7HEfruasPLwcluVCmByCFD with Params: {} returned 403 due to None

❌ Error retrieving valence for You're Making A Mistake by The Platters: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2hECDE2rtiNWCjxviTO5W4:
 None, reason: None
❌ Error retrieving valence for Don't Pity Me by Dion & The Belmonts: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7HEfruasPLwcluVCmByCFD:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2tvZLWkQT8hYWV5zbl6TVx with Params: {} returned 403 due to None

❌ Error retrieving valence for Fire Of Love by Jody Reynolds: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2tvZLWkQT8hYWV5zbl6TVx:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0M8UX5vJCoWLnht1Wzg5Ez with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4XNdVbvpFie1lALgHdwrPl with Params: {} returned 403 due to None

❌ Error retrieving valence for Jennie Lee by Jan & Arnie: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0M8UX5vJCoWLnht1Wzg5Ez:
 None, reason: None
❌ Error retrieving valence for You Need Hands by Eydie Gorme: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4XNdVbvpFie1lALgHdwrPl:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3p5UOl5bsy733j2IxZssCH with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2o7Bb5GQgWElsdcZqtbqXB with Params: {} returned 403 due to None

❌ Error retrieving valence for My Lucky Love by Doug Franklin With The Bluenotes: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3p5UOl5bsy733j2IxZssCH:
 None, reason: None
❌ Error retrieving valence for Rocka-Conga by The Applejacks: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2o7Bb5GQgWElsdcZqtbqXB:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2pnPe4pJtq7689i5ydzvJJ with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6RC1qjcUw89hjt5ZufYVvF with Params: {} returned 403 due to None

❌ Error retrieving valence for Run Rudolph Run by Chuck Berry: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2pnPe4pJtq7689i5ydzvJJ:
 None, reason: None
❌ Error retrieving valence for Please Love Me Forever by Tommy Edwards: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6RC1qjcUw89hjt5ZufYVvF:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5MhbknogEFZV1E3Zkl4pBy with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0QY78jejWg0JMo3IJABG4l with Params: {} returned 403 due to None

❌ Error retrieving valence for Where The Blue Of The Night by Tommy Mara: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5MhbknogEFZV1E3Zkl4pBy:
 None, reason: None
❌ Error retrieving valence for High School Confidential by Jerry Lee Lewis And His Pumping Piano: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0QY78jejWg0JMo3IJABG4l:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1Nl6aWCxAbZqr4FLwgeFSq with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7vRTXMx5g291Zirz6aWXs8 with Params: {} returned 403 due to None

❌ Error retrieving valence for Nothin' Shakin' by Eddie Fontaine: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1Nl6aWCxAbZqr4FLwgeFSq:
 None, reason: None
❌ Error retrieving valence for Wendy, Wendy by The Four Coins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7vRTXMx5g291Zirz6aWXs8:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1t6rnzqkPfEbAA0wJ1nF7G with Params: {} returned 403 due to None

❌ Error retrieving valence for Lucky Ladybug by Billy & Lillie: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1t6rnzqkPfEbAA0wJ1nF7G:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=44iexWZVU1YqTFjkJhVHFB with Params: {} returned 403 due to None

❌ Error retrieving valence for Diamond Ring by Jerry Wallace: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=44iexWZVU1YqTFjkJhVHFB:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5ZbmyXPF6h1JCCQiFQaTie with Params: {} returned 403 due to None

❌ Error retrieving valence for Little Red Riding Hood by Big Bopper: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5ZbmyXPF6h1JCCQiFQaTie:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7tyuIX684fvLD5oipSb0Y3 with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0mLOjNE7eLDP7LpqcO1hwd with Params: {} returned 403 due to None

❌ Error retrieving valence for You're A Sweetheart by Little Willie John: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7tyuIX684fvLD5oipSb0Y3:
 None, reason: None
❌ Error retrieving valence for Just Young by Paul Anka: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0mLOjNE7eLDP7LpqcO1hwd:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3mBqSjoj9R22gct558sIgG with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7dblNGnRXEBrVJunazs2U5 with Params: {} returned 403 due to None

❌ Error retrieving valence for Merry Christmas Baby by Chuck Berry: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3mBqSjoj9R22gct558sIgG:
 None, reason: None
❌ Error retrieving valence for All I Have To Do Is Dream by The Everly Brothers: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7dblNGnRXEBrVJunazs2U5:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4j80rvP2WPxSUAEQVEa7BK with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5OaNbW3mlqRHggGdXVttc0 with Params: {} returned 403 due to None

❌ Error retrieving valence for Young And Warm And Wonderful by Tony Bennett: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4j80rvP2WPxSUAEQVEa7BK:
 None, reason: None
❌ Error retrieving valence for Come Prima (Koma Preema) by Polly Bergen: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5OaNbW3mlqRHggGdXVttc0:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0bCO313oqViNrFc8Ln9bXO with Params: {} returned 403 due to None
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3xHaS8wE5x0T9mAQceEhiN with Params: {} returned 403 due to None

❌ Error retrieving valence for The Fool And The Angel by Bobby Helms: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0bCO313oqViNrFc8Ln9bXO:
 None, reason: None
❌ Error retrieving valence for I Want To Be Happy Cha Cha by The Tommy Dorsey Orchestra Starring Warren Covington: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3xHaS8wE5x0T9mAQceEhiN:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=32h9rYPPVLqLkFrGNGqvk6 with Params: {} returned 403 due to None

❌ Error retrieving valence for White Bucks And Saddle Shoes by Bobby Pedrick, Jr.: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=32h9rYPPVLqLkFrGNGqvk6:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=672bYvh0ygZMrUvRr6hN4P with Params: {} returned 403 due to None

❌ Error retrieving valence for Drip Drop by The Drifters: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=672bYvh0ygZMrUvRr6hN4P:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=32nnT2rB4yu7hm6BznJbfK with Params: {} returned 403 due to None

❌ Error retrieving valence for Borrowed Dreams by Bobby Helms: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=32nnT2rB4yu7hm6BznJbfK:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7c0ZUiqjVB8pMnRGUnVDF0 with Params: {} returned 403 due to None

❌ Error retrieving valence for Delicious! by Jim Backus & Friend: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7c0ZUiqjVB8pMnRGUnVDF0:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0GsNzZNqLPrNnJswoQOCtO with Params: {} returned 403 due to None

❌ Error retrieving valence for Green Chri$tma$ by Stan Freberg: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0GsNzZNqLPrNnJswoQOCtO:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0USA1Xw1tdIMPzr3sB8AjS with Params: {} returned 403 due to None

❌ Error retrieving valence for Strange Are The Ways Of Love by Gogi Grant: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0USA1Xw1tdIMPzr3sB8AjS:
 None, reason: None

WARNING:root:Your application has reached a rate/request limit. Retry will occur after: 1
ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=63aVPmITmcktSPFxWIYMY9 with Params: {} returned 403 due to None

❌ Error retrieving valence for (It's Been A Long Time) Pretty Baby by Gino & Gina: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=63aVPmITmcktSPFxWIYMY9:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1XQBUFUSCycU2QLayJU97u with Params: {} returned 403 due to None

❌ Error retrieving valence for Your Cheatin' Heart by George Hamilton IV: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1XQBUFUSCycU2QLayJU97u:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4HwMCwpjAKQGnmdXwiKPON with Params: {} returned 403 due to None

❌ Error retrieving valence for Straighten Up & Fly Right by DeJohn Sisters: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4HwMCwpjAKQGnmdXwiKPON:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3B31wgtPcuqbs5oNNhPgu0 with Params: {} returned 403 due to None

❌ Error retrieving valence for Teasin' by Quaker City Boys: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3B31wgtPcuqbs5oNNhPgu0:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4J0JFGn4avOMbTAFPKBbpF with Params: {} returned 403 due to None

❌ Error retrieving valence for Dreamy Eyes by Johnny Tillotson: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4J0JFGn4avOMbTAFPKBbpF:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=77gBB0YPfVbyiPaz03A1HF with Params: {} returned 403 due to None

❌ Error retrieving valence for Joe Joe Gunne by Chuck Berry: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=77gBB0YPfVbyiPaz03A1HF:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4JI46dgL9fLzqSIr9sAhug with Params: {} returned 403 due to None

❌ Error retrieving valence for The World Outside by Roger Williams: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4JI46dgL9fLzqSIr9sAhug:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3hScEmuagcQ0TvoJa5oFyI with Params: {} returned 403 due to None

❌ Error retrieving valence for White Christmas by Bing Crosby: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3hScEmuagcQ0TvoJa5oFyI:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6VbIr50kEUMKTC1hyiA51b with Params: {} returned 403 due to None

❌ Error retrieving valence for Try The Impossible by Lee Andrews And The Hearts: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6VbIr50kEUMKTC1hyiA51b:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=31nERAOcpjpq7zxXpJTwfX with Params: {} returned 403 due to None

❌ Error retrieving valence for Just Like In The Movies by The Upbeats: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=31nERAOcpjpq7zxXpJTwfX:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0hglGc81w2lUPvwLHlABHr with Params: {} returned 403 due to None

❌ Error retrieving valence for Devotion by Janice Harper: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0hglGc81w2lUPvwLHlABHr:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3Xj06XtazKsy9S0FAHIAcF with Params: {} returned 403 due to None

❌ Error retrieving valence for Almost In Your Arms by Johnny Nash: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3Xj06XtazKsy9S0FAHIAcF:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5pHGVam2BADarGk2sHpgmA with Params: {} returned 403 due to None

❌ Error retrieving valence for Fool's Paradise by The Crickets: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5pHGVam2BADarGk2sHpgmA:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5zH2eUNjX4c4SG5TwiYPDo with Params: {} returned 403 due to None

❌ Error retrieving valence for Don't Go Home by The Playmates: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5zH2eUNjX4c4SG5TwiYPDo:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3RLCKTwryqRgsRlkCNKnZE with Params: {} returned 403 due to None

❌ Error retrieving valence for What Little Girl by Frankie Avalon: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3RLCKTwryqRgsRlkCNKnZE:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=7f4rOYT3NqBWnTCRc2cRpB with Params: {} returned 403 due to None

❌ Error retrieving valence for For Your Love by Ed Townsend: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=7f4rOYT3NqBWnTCRc2cRpB:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=53hRWsxmu9KjGwXEev72gc with Params: {} returned 403 due to None

❌ Error retrieving valence for A House, A Car And A Wedding Ring by Dale Hawkins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=53hRWsxmu9KjGwXEev72gc:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5Qbie4S6sDDMOjwodcEhgA with Params: {} returned 403 due to None

❌ Error retrieving valence for Harvey's Got A Girl Friend by Royal Teens: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5Qbie4S6sDDMOjwodcEhgA:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4ILiMETdCJ58TJa08p7KmB with Params: {} returned 403 due to None

❌ Error retrieving valence for Week End by The Kingsmen: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4ILiMETdCJ58TJa08p7KmB:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0uJAxCtCwjSnFn6HPOoIur with Params: {} returned 403 due to None

❌ Error retrieving valence for Blip Blop by Bill Doggett: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0uJAxCtCwjSnFn6HPOoIur:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=2wh41h8XJWXIds4gPpfOzN with Params: {} returned 403 due to None

❌ Error retrieving valence for Gas Money by Jan & Arnie: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=2wh41h8XJWXIds4gPpfOzN:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5tbVicKU2HHCbSJivpvj8T with Params: {} returned 403 due to None

❌ Error retrieving valence for Little Mary by Fats Domino: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5tbVicKU2HHCbSJivpvj8T:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0KayDFomB8iDyAdOpKfKTK with Params: {} returned 403 due to None

❌ Error retrieving valence for Big Man by The Four Preps: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0KayDFomB8iDyAdOpKfKTK:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=39aMG47Bvx6PF268MYlmIF with Params: {} returned 403 due to None

❌ Error retrieving valence for Lean Jean by Bill Haley And His Comets: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=39aMG47Bvx6PF268MYlmIF:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5xmHm4hPIbyo4u5ouCOEeq with Params: {} returned 403 due to None

❌ Error retrieving valence for The Day I Died by The Playmates: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5xmHm4hPIbyo4u5ouCOEeq:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5D94XZ4AA0oIdvOxaJEw3W with Params: {} returned 403 due to None

❌ Error retrieving valence for Jealousy by Kitty Wells: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5D94XZ4AA0oIdvOxaJEw3W:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4NNZRExiuUdECcw72SSNhH with Params: {} returned 403 due to None

❌ Error retrieving valence for Op by The Honeycones: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4NNZRExiuUdECcw72SSNhH:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6E3IjF7RGqLQTDwWZBRL9J with Params: {} returned 403 due to None

❌ Error retrieving valence for Crazy Country Hop by Johnny Otis: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6E3IjF7RGqLQTDwWZBRL9J:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=41Sjl3fkrmoU4Xv0kaf6kQ with Params: {} returned 403 due to None

❌ Error retrieving valence for Prisoner's Song by Warren Storm: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=41Sjl3fkrmoU4Xv0kaf6kQ:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5S8VwnB4sLi6W0lYTWYylu with Params: {} returned 403 due to None

❌ Error retrieving valence for Got A Match? by Frank Gallup: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5S8VwnB4sLi6W0lYTWYylu:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=1nXTM2CVdaoCySSD5kgt3J with Params: {} returned 403 due to None

❌ Error retrieving valence for Big Brown Eyes by The Redjacks: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=1nXTM2CVdaoCySSD5kgt3J:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=6xqb6DesHnFeWe5uZpFXzh with Params: {} returned 403 due to None

❌ Error retrieving valence for Philadelphia U.S.A. by Art Lund: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=6xqb6DesHnFeWe5uZpFXzh:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0yhQGpjIEFr8yEGarlwzHF with Params: {} returned 403 due to None

❌ Error retrieving valence for The Hawaiian Wedding Song (Ke Kali Nei Au) by Andy Williams: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0yhQGpjIEFr8yEGarlwzHF:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=50KVuwrLS1KVwjobyeEAwj with Params: {} returned 403 due to None

❌ Error retrieving valence for Up Until Now by Johnnie Ray: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=50KVuwrLS1KVwjobyeEAwj:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=53LYRp9hLdpaffCkE08HE6 with Params: {} returned 403 due to None

❌ Error retrieving valence for Blue Hawaii by Billy Vaughn And His Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=53LYRp9hLdpaffCkE08HE6:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=5LakieII7Kepnxep36rJJm with Params: {} returned 403 due to None

❌ Error retrieving valence for Bullwhip Rock by Cyclones: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=5LakieII7Kepnxep36rJJm:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=4xQcdett4ExN4yxCxBw7VB with Params: {} returned 403 due to None

❌ Error retrieving valence for Rockhouse (Part 2) by Ray Charles and his Orchestra: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=4xQcdett4ExN4yxCxBw7VB:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=0lekgsdqWTJRKcExgH1xk7 with Params: {} returned 403 due to None

❌ Error retrieving valence for Little Brass Band by David Seville: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=0lekgsdqWTJRKcExgH1xk7:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3nOBuIua3UVvL8AHibaaAJ with Params: {} returned 403 due to None

❌ Error retrieving valence for Just Married by Marty Robbins: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3nOBuIua3UVvL8AHibaaAJ:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3zFwGvu3pZ6gquRS07LZSZ with Params: {} returned 403 due to None

❌ Error retrieving valence for The Worryin' Kind by Tommy Sands And The Raiders: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3zFwGvu3pZ6gquRS07LZSZ:
 None, reason: None

ERROR:spotipy.client:HTTP Error for GET to https://api.spotify.com/v1/audio-features/?ids=3XYoEYCdKEQLC9VK7mcrNQ with Params: {} returned 403 due to None

❌ Error retrieving valence for The Bird On My Head by David Seville: http status: 403, code: -1 - https://api.spotify.com/v1/audio-features/?ids=3XYoEYCdKEQLC9VK7mcrNQ:
 None, reason: None

KeyboardInterrupt: